### ISSUE TITLE
Demo appears to be broken

### ISSUE THREAD

**Issue by jayfk** [hopsoft/stimulus_reflex#101]
The demo at http://expo.stimulusreflex.com/ seems to be broken.

**Comment by pjforde1978** [comment]
Really sorry about this. Temp site: https://expo-pjf.herokuapp.com/

**Comment by hopsoft** [comment]
The expo site has proven popular enough to have exhausted Heroku's free dyno hours. I upgraded to a paid plan so we're back in business.

**Comment by rubiii** [comment]
Hey. First of all, thanks for your work here!
I'm just starting to check out the project and also noticed that the demo link in the Readme is broken.
Unfortunately, the Heroku app seems to be down as well.

I would suggest either getting the demo back up and fixing the link or removing it from now.
Let me know if I can help.
