### ISSUE TITLE
Would it work with Webhooks updates

### ISSUE THREAD

**Issue by adrienpoly** [hopsoft/stimulus_reflex#13]
Hey not an issue here more of a question.

I was wondering if I could use Reflex to update in realtime my UI when I receive a webhook?

I am working on several Stripe SCA upgrade projects and once the payment is sent then my success page needs to refresh when I receive the Stripe confirmation webhook and that I have fulfilled the order. 
Currently, I am doing this with either a simple polling or with action cable.

Would Reflex work for such use case?

Thanks for this promising project

**Comment by hopsoft** [comment]
This library is more focused on reactive updates triggered on the client. I'd recommend looking at the underlying library [CableReady](https://github.com/hopsoft/cable_ready) for your described use case. It will make updating the client DOM via ActionCable a little simpler for you.

**Comment by adrienpoly** [comment]
Thanks, totally makes sens
