### ISSUE TITLE
Pass element tagname in reflex

### ISSUE THREAD

**Issue by julianrubisch** [hopsoft/stimulus_reflex#137]
# Feature Request

it would be feasible to access the tagname of the DOM element that triggered the reflex (and potentially other properties as well?)

## Is your feature request related to a problem?

in some context it occured to me that it would be feasible not only to have `checked`, `selected` and `value(s)` attributes, but also to be able to discern between `SELECT`, `OPTGROUP` etc. etc. 

## Describe the solution you'd like

Pass the element tagname through the ActionCable connection up to the reflex

## Additional context

If anyone could point me to the relevant parts of the source, I'd be happy to prepare a PR

**Comment by leastbad** [comment]
Yes! Cool. Consider adding element.tagName to attributes.js in extractElementAttributes function.
