### ISSUE TITLE
Allow extractElementAttributes to use a checkbox list

### ISSUE THREAD

**Issue by julianrubisch** [hopsoft/stimulus_reflex#147]
# Feature Request

`extractElementAttributes` for the moment returns multiple values for `select` tags with `multiple: true`:

https://github.com/hopsoft/stimulus_reflex/blob/480ee76dccf4ddc212602d1c3dee01216b6369ab/javascript/attributes.js#L37

A common scenario is to use a checkbox list for an association collection, as in `collection_check_boxes`:

https://devdocs.io/rails~6.0/actionview/helpers/formoptionshelper#method-i-collection_check_boxes

It would be nice if SR supported that out of the box.

## Describe the solution you'd like

The hidden complexity lies in the fact that we'd have to consider multiple elements in `extractElementAttributes`, not just the one triggering the reflex. Still I think a library such as SR should take on that complexity instead of imposing it on the back end developer.

Specifically, I discovered this shortage when working on the permalink expo example and trying to employ a button group: https://github.com/hopsoft/stimulus_reflex_expo/pull/26/files#diff-23c58647594fccfb30d0b54554851d59R15

**Comment by hopsoft** [comment]
Are you thinking we should marshal attributes only for `checked` and `selected` options? Then store them under something like `attrs.checkedOptions = [{...},{...},...]` and `attrs.selectedOptions = [{...},{...},...]`?

**Comment by julianrubisch** [comment]
Right. On the server side you’d get an array of checked options as in a multiple select
