### ISSUE TITLE
Reflex callbacks

### ISSUE THREAD

**Issue by julianrubisch** [hopsoft/stimulus_reflex#155]
# Feature Request

Reflexes could support before, around and after actions like controllers. Could help DRY up some reflexes that I set up out in the wild ;-)

## Is your feature request related to a problem?

Repetitive code in reflex actions. 

## Describe the solution you'd like

Take a look at https://github.com/rails/rails/blob/157920aead96865e3135f496c09ace607d5620dc/actionpack/lib/abstract_controller/callbacks.rb

**Comment by leastbad** [comment]
I can get behind this, and maybe even pair with you on it.

Could you check out #80 and the conversation there? @hopsoft mentioned accomplishing the same results via callbacks. I'm game, but I still don't exactly understand how that would work. :)
