### ISSUE TITLE
Unable to register the ActionCable Consumer

### ISSUE THREAD

**Issue by moveson** [hopsoft/stimulus_reflex#156]
# Bug Report

I was using StimulusReflex successfully, but it has suddenly started giving me this error in console: "StimulusReflex was unable to register the ActionCable consumer. Don't worry, everything should still work."

I'm worried. Any idea what's going on here?

**Comment by leastbad** [comment]
Very sorry, our 3.0 release had a bug. Can you try 3.0.1, please? Don’t forget to update the JS package at the same time (or you’ll do what i always do).

**Comment by moveson** [comment]
I'm confused by this response. I was using 3.0.0 and was not getting an error. I upgraded to 3.1.2 and now I am seeing the error. I don't believe a version 3.0.1 exists.

**Comment by leastbad** [comment]
I am very sorry: i was responding from my phone. What i should have said was “upgrade to the latest”.
