### ISSUE TITLE
Integration tests for stimulus-reflex

### ISSUE THREAD

**Issue by jonathan-s** [hopsoft/stimulus_reflex#162]
Since there are quite a few moving parts that gets this working I thought that perhaps it would be a good idea to have integration tests using cypress.io. One good reason for considering cypress.io is that you'll write tests against browser behaviour, which means that you'll see how the javascript and ruby code works together. 

I wanted to open this issue to collect ideas on things that would need to get tested, edge cases that should work and perhaps haven't at some point etc.

These are some things that I thought of on top of my mind. 

- All possible actions work together with cable ready. 
- Defining a controller manually works properly
- Only using html without defining a js controller works.

**Comment by SampsonCrowley** [comment]
@jonathan-s Whoops! I think our issues (mine: #164 ) are a little too closely related; I guess I should have read through yours instead of just assuming it was about a specific tool you are using playing nicely with this library. Would you mind removing `cypress.io` from the title, to allow for tool agnostic suggestions? `cypress.io` should be a suggested way to do it, not the feature of the issue here; which is really about making tests easier for end users.

I'll close #164 in favor of this one to keep the discussion here.

**Comment by jonathan-s** [comment]
Just to show how things would look like using cypress.io 

This is the folder structure that cypress.io initializes
https://github.com/jonathan-s/django-sockpuppet/tree/master/cypress

and you'll find a simple test here:
https://github.com/jonathan-s/django-sockpuppet/blob/master/cypress/integration/websocket_spec.js

**Comment by SampsonCrowley** [comment]
Cypress definitely makes End-to-End testing easier, but I think we would be better off using tools that 1. already a part of the Rails ecosystem, and 2. are not reliant on a paid service.

I think pre-defined [System tests](https://guides.rubyonrails.org/testing.html#functional-and-system-testing) in rails are the better way to go

**Comment by jonathan-s** [comment]
That seems like a valid option as well. Though I'd like to note that cypress is paid to an even lesser degree than say travis that we all use and love. 

Ultimately, I think the one who starts making this has more decision power than me :) (because I don't know enough ruby to make some parts that are required).

**Comment by julianrubisch** [comment]
AFAIK @hopsoft started setting up a testrigor suite that runs against expo.stimulusreflex.com.

Still, integration tests would be good to have, but it would require setting up a dummy rails app and setting up CI for system tests, which is altogether quite large a task.

If anyone would set up a `test/dummy` app in a PR, that would be a good start though - what do you think @hopsoft , @leastbad , @andrewmcodes ?

**Comment by leastbad** [comment]
At this point, running the integration tests on the Expo project is the primary vehicle for testing SR. I know that there are some JS tests making their way into the framework as well.

Finally and perhaps most importantly, see https://github.com/podia/stimulus_reflex_testing for tools to test SR-enabled apps.
