### ISSUE TITLE
Testing Integrations

### ISSUE THREAD

**Issue by SampsonCrowley** [hopsoft/stimulus_reflex#164]
# Feature Request

As we all know, the most important part of developing things the right way is proper testing! From what I could find in the docs, this library doesn't add any test helpers or examples of testing a `Reflex`.

1. Are there any helpers with testing that reflexes are doing what they should?
2. If not should we build some?

## Describe the solution you'd like

I think both `test/unit` and `rspec` integrations would be useful to and cover the majority of the community

If not, at least some examples in the docs of how to test

**Comment by SampsonCrowley** [comment]
Closing in favor of #162; which I thought was about incompatible libraries

**Comment by jonathan-s** [comment]
I've changed the title :)
