### ISSUE TITLE
CableReady detected an error in morph! Event is not a constructor

### ISSUE THREAD

**Issue by dalezak** [hopsoft/stimulus_reflex#165]
# Bug Report

Getting the error `CableReady detected an error in morph! Event is not a constructor` when trying to update page content.

## Describe the bug

I'm trying to get simple pagination working with a Load More button loading the next set of records, however the content isn't being updated.

## To Reproduce

I added a `console.error` to the `cable_ready` package, which displays:

```
cable_ready.js TypeError: Event is not a constructor
    at dispatch (cable_ready.js:15)
    at Object.morph (cable_ready.js:57)
    at Object.perform (cable_ready.js:197)
    at Subscription.received (stimulus_reflex.js:94)
    at action_cable.js:536
    at Array.map (<anonymous>)
    at Subscriptions.notify (action_cable.js:535)
    at Connection.message (action_cable.js:369)
perform | @ | cable_ready.js:199
received | @ | stimulus_reflex.js:94
(anonymous) | @ | action_cable.js:536
notify | @ | action_cable.js:535
message | @ | action_cable.js:369
```

## Screenshots

![Screenshot 2020-04-23 09 32 02](https://user-images.githubusercontent.com/91811/80118305-75929600-8545-11ea-9863-d460bd3aabe7.png)

### StimulusReflex

- Gem: 3.1.3
- Node package: 3.1.3

### External tools

- Ruby: 2.6.5
- Rails: 6.0.2
- Node: 10.14.1

### Browser

- Browser: Chrome
- Version: 81.0.4044.113 (Official Build) (64-bit)

**Comment by dalezak** [comment]
I noticed for the morph, that the entire body was trying to be transformed. Is this normal? Shouldn't only the changed area be updated?

**Comment by leastbad** [comment]
The default behaviour is to morph body. You can use `data-reflex-root` to change the target. Check out the Scoping section of the documentation.

Are you still seeing the strange JS error?

**Comment by dalezak** [comment]
_Ah-ha!_ So I had enabled Stimulus Reflex into my project that was already using Vue. When I comment out the Vue code from `app/javascript/packs`, then _my Reflexes work_!

I am currently using Vue components sprinkled throughout my Rails app for dynamic elements, but considering using Stimulus for those elements instead.

Can Stimulus Reflex work alongside Vue? Or should you choose one or the other?

**Comment by leastbad** [comment]
If you're asking my opinion, I think that you should purge Vue with fire. :fire::fire::fire:

There's two general approaches that you can currently take to hopefully make them work together. First, you can tell SR to only replace a particular container by setting a `data-reflex-root` as described in the scoping section.

The other thing you can do is put a `data-reflex-permanent` attribute on the DOM element that contains your Vue component.

I'd be curious for you to try both techniques and let me know whether either or both of them work. You'd be doing us a favor!

**Comment by dalezak** [comment]
Ok, thanks for the suggestions! 

I always liked `js.erb`, have preferred using Vue over Angular or React, but excited to return to the Ruby world with Stimulus Reflex :+1:

**Comment by leastbad** [comment]
We’re happy to have you on board!

Are you on Discord?
