### ISSUE TITLE
Warn about enabling Rails after running stimulus reflex' initializer

### ISSUE THREAD

**Issue by gafemoyano** [hopsoft/stimulus_reflex#185]
# Bug Report
So this just tripped up a member of my team and me, and I think the docs should warn about this particular scenario since Devise is fairly popular.

## Describe the bug

If you don't have Rails cache turned on during development and you're using Devise then users can't sign up and they get a rather confusing error InvalidAuthenticityToken.

## To Reproduce

- Spin up a rails project that uses devise
- Go to a route that has the `authanticate_user!` action
- Put in your credentials
- InvalidAuthenticityToken Exception
## Expected behavior

I don't think stimulus_reflex should do anything differently, just add a warning in the documentation to help users who bump into this debug it.

## Screenshots or reproduction
![image](https://user-images.githubusercontent.com/1516349/81016578-54c01f80-8e26-11ea-8f7b-149172dc5a59.png)

### StimulusReflex

- Gem: [e.g. 2.0.1]
- Node package: [e.g. 2.0.1]

### External tools

- Ruby: 2.6.3
- Rails:  6.0..2.2
- Node: 10.19.0

### Browser

- Chrome Firefox

**Comment by leastbad** [comment]
Turning on development mode caching is part of the SR install task and explicitly mentioned in the setup steps.

https://docs.stimulusreflex.com/setup

I really am sorry that you lost time to this, but you skipped one of the only steps in the setup process. It’s not just a Devise issue.

**Comment by gafemoyano** [comment]
Ohh you’re right is there. I think I didn’t word this correctly. I did in fact run the commands described there and I kept working on my feature branch without issue.
Then when it got merge and **someone else** without caching enabled experienced the issue and it took quite a while to figure out why.

So even if it **is** on the installation steps I think it might be worth considering adding a warning or a gotcha somewhere just in case someone comes across this.

It’s also easy to forget about the :cache_store flag in the app config and sometimes you might want to disable cache in development for various reasons.

I’m happy to close the issue though if there’s no further action to consider.

**Comment by leastbad** [comment]
@hopsoft do you think it makes sense to tell people in development mode that they need to turn on caching if it’s not currently on? I’m thinking via console message in channel.rb?

**Comment by julianrubisch** [comment]
Fwiw I had exactly the same situation on a project yesterday

**Comment by leastbad** [comment]
@julianrubisch good enough for me! up for a PR?

**Comment by julianrubisch** [comment]
I was thinking we could even show a badge in the UI in development if Session store == cookie or if it’s cache store and caching is disabled. 

Or is that too obtrusive?

**Comment by leastbad** [comment]
It's definitely *ballsy*.

It's such a shame that puma's stdout doesn't support ANSI art animations.

**Comment by julianrubisch** [comment]
Could you translate that for me? 😂

**Comment by leastbad** [comment]
Yes, sorry!

I don't know if it's *too* obtrusive, but it's impressively obtrusive. I had thought a console alert when booting the app might suffice, but I admit I'd be amused to see how you'd insert such a badge, given the diversity of what applications can emit when a page is requested.

In the late 80s BBS scene, there was a subculture of artistic geeks that would use extended ANSI codes (which could do lots of things - like make the speaker beep - in addition to changing the color) to create elaborate animations that would play if you had a modern enough terminal program and your modem was good enough.

I looked on Youtube: https://www.youtube.com/watch?v=N4cERxBdkNk&list=PL995C3D53385901FD&index=1
