### ISSUE TITLE
 The ActionCable connection is not open! `this.isActionCableConnectionOpen()` must return true before calling `this.stimulate()`

### ISSUE THREAD

**Issue by futura** [hopsoft/stimulus_reflex#187]
# Bug Report

## Describe the bug

In production, clicking on a reflex gives the error:

``` The ActionCable connection is not open! `this.isActionCableConnectionOpen()` must return true before calling `this.stimulate()` ```

## To Reproduce

I was thinking the error was in ActionCable, but now I'm not sure where the error is occurring.

Using the Hello, Reflex example at https://docs.stimulusreflex.com/quickstart, this is working in development, but not in production.

## Expected behavior

In development, clicking on "increment" is working to increment the counter. In production, I get the error.

Trying to log the connection ...

```
module ApplicationCable
  class Connection < ActionCable::Connection::Base
    def connect
      Rails.logger.level = Logger::DEBUG
      Rails.logger.info "Connected to ActionCable!"
    end
  end
end
```

I'm getting "Connected to ActionCable!" in my production log, so I assume the cable is connected.

## Screenshots or reproduction

Live example is here:
http://supervise.casehandler.com

### StimulusReflex

- Gem: 3.1.4
- Node package: 3.1.4

### External tools

- Ruby: 2.7.0
- Rails: 6.2.2
- Node: 14.1.0

- Passenger: 6.0.4
- Nginx

### Browser

- Browser Firefox Developer Edition
- Version 77.0b1

**Comment by jonathan-s** [comment]
This is what I'm seeing when I visit the website. 
<img width="395" alt="Screenshot 2020-05-05 at 22 59 17" src="https://user-images.githubusercontent.com/2124818/81115527-1f99f700-8f24-11ea-8439-5888e4bfbd34.png">

So it seems like the actioncable in some way is not entirely correctly set up.

**Comment by futura** [comment]
Thanks, this doesn't surprise me. First time using ActionCable ...

**Comment by leastbad** [comment]
Hi @futura! Let's get you sorted. Fortunately or unfortunately - depending on your perspective - the fact that it's working does point to a configuration issue with how Passenger is (or isn't) upgrading connections to websockets.

When I look at the websockets connections tab in the Network inspector, I see that it opens a new cable connection every 5-10 seconds after clicking the link. Each attempt shows the connection sending a message to the server but not receiving any reply. If you try this in development, you'll see the server respond here.

Can you try a really basic ActionCable example and see if it works? Like you said, we need to narrow down where this is happening. I suspect that Passenger is causing us some grief.

Are you seeing action cable errors in your production log? Try temporarily setting your production.rb: `config.log_level = :warn`

**Comment by futura** [comment]
I changed the log level and Nginx error log still is empty.

I'm wondering if it's related to this:

[https://stackoverflow.com/questions/47807569/actioncable-in-production-repeated-101-responses](https://stackoverflow.com/questions/47807569/actioncable-in-production-repeated-101-responses)

In development, the cable only opens once and persists. In production, I get 101 after 101 and occasionally maybe 502. I'm using a subdomain, so maybe that's an issue?

I have this in routes.rb:

```
  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
```

Virtual host config:

```
server {
  listen 80;
  server_name supervise.casehandler.com;

  # Tell Nginx and Passenger where your app’s ‘public’ directory is
  root /home/dwayne/apps/supervise/public;

  access_log /home/dwayne/apps/supervise/log/nginx.access.log;
  error_log /home/dwayne/apps/supervise/log/nginx.error.log warn;

  # Turn on Passenger
  passenger_enabled on;
  passenger_ruby /usr/local/rvm/gems/ruby-2.7.0@supervise/wrappers/ruby;

  # ActionCable
  location /cable {
    passenger_app_group_name supervise_action_cable;
    passenger_force_max_concurrent_requests_per_process 0;
  }

}
```

In environments/production.rb:

```
  config.action_cable.url = ['wss://supervise.casehandler.com/cable', 'ws://supervise.casehandler.com/cable']
  config.action_cable.allowed_request_origins = [
    'http://supervise.casehandler.com'
  ]
```

Sorry, it's looking like this isn't a StimulusReflex issue, but thanks for your help. If anything comes to mind, I'd love to hear it.

I'm loving StimulusReflex so far.

**Comment by futura** [comment]
Solved. The one thing I didn't share here was config/cable.yml. My redis url was wrong.

**Comment by leastbad** [comment]
That’s great news! Nice catch.

**Comment by leastbad** [comment]
Try
```yaml
development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/0" } %>

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/0" } %>
```

**Comment by TimeTravelerFromNow** [comment]
Thanks for the fast response, I'm very new to all this, would I need a redis server running? If so can you share a guide for ubuntu 20.04, I'm using mina for deployment and could probably add a command in my deploy.rb to start the redis server.
```
  deploy do
    # Put things that will set up an empty directory into a fully set-up
    # instance of your project.
    invoke :'git:clone'
    invoke :'deploy:link_shared_paths'
    invoke :'bundle:install'
    invoke :'rails:db_migrate'
    invoke :'rails:assets_precompile'
    on :launch do
      command "sudo systemctl restart #{fetch(:user)}"
    end
  end

```
