### ISSUE TITLE
Add a halted lifecycle event

### ISSUE THREAD

**Issue by hopsoft** [hopsoft/stimulus_reflex#190]
# Feature Request

## Is your feature request related to a problem?

Currently clients cannot react to `halted` noop reflexes.

## Describe the solution you'd like
When a reflex callback chain is halted, the client is not made aware of this condition. This is because the lifecycle currently only supports:

- before
- success
- error
- after

This proposal would introduce a `halted` lifecycle event.

- before
- success
- error
- halted 👈 
- after

Adding a `halted` lifecycle event would allow clients to handle things properly and cleanup any UI tweaks made in the `before` event.

**Comment by leastbad** [comment]
OMG I just spent half an hour trying to find the PR where you added the halted client-side callbacks 🤯 lol

**Comment by hopsoft** [comment]
@leastbad Not sure if you found it, but here it is. https://github.com/hopsoft/stimulus_reflex/pull/160/files#diff-bf91f9c76097698b1ca61d4d3f3cab08R39

**Comment by leastbad** [comment]
That’s the server implementation. I’m talking about the client side; your issue is a proposal, right?

**Comment by hopsoft** [comment]
@leastbad Yes this is a feature proposal.
