### ISSUE TITLE
Accessing dataset as before is returning nil

### ISSUE THREAD

**Issue by jasoncharnes** [hopsoft/stimulus_reflex#218]
# Bug Report

## Describe the bug

With (what I assume to be) the update in #210 I'm unable to access my dataset as I was, previously. It's totally possible I'm misunderstanding something, but when I point to master this happened in our codebase.

## To Reproduce

```erb
<div data-email-id="<%= @email.id %>" data-reflex="click->EmailReflex#take_action">
<div>
```

```ruby
class EmailReflex < ApplicationReflex
  def take_action
    # before the update
    element.dataset.dig("email-id") # => "10"
    # after the update
    element.dataset.dig("email-id") # => nil
    element.dataset.email_id # => nil
    element.data.email_id # => undefined method email_id for nil
    element.data_email_id # => "10"
  end
end
```

## Expected behavior

```erb
<div data-email-id="<%= @email.id %>" data-reflex="click->EmailReflex#take_action">
<div>
```

```ruby
class EmailReflex < ApplicationReflex
  def take_action
    # before the update
    element.dataset.dig("email-id") # => "10"
    # after the update
    element.dataset.dig("email-id") # => "10"
    element.dataset.dig(:email_id) # => "10"
    element.dataset.email_id # => "10"
  end
end
```
### StimulusReflex

- Gem: [master]
- Node package: [master]

### External tools

- Ruby: [2.6.6]
- Rails: [5.2.4.3]
- Node: [13.11]

### Browser

- Browser [safari]
- Version [13.1]

**Comment by jasoncharnes** [comment]
HAHAHAHA IGNORE ME

I think this was an issue without pointing to GitHub being behind in my `Gemfile`

https://getyarn.io/yarn-clip/efec74c6-91fa-4488-9706-084cbb755f02

Sorry for the noise love you all

**Comment by hopsoft** [comment]
Not really sure how I feel about this but it would support the Hash method `dig`. https://github.com/hopsoft/stimulus_reflex/pull/214/commits/22188d1fa3a10e0ed6db801d2281db25b8b0d772

**Comment by jasoncharnes** [comment]
FWIW I believe dig worked as expected, I was just behind in my Gemfile (somehow)

**Comment by jasoncharnes** [comment]
Confirmed, its works.

```ruby
[1] pry(#<CMS::CampaignReflex>)> element.dataset.signed_drip_email_id
=> "Blah blah"
[2] pry(#<CMS::CampaignReflex>)> element.dataset.dig("signed-drip-email-id")
=> "Blah blah"
```
