### ISSUE TITLE
Session lost after throw :abort

### ISSUE THREAD

**Issue by joshleblanc** [hopsoft/stimulus_reflex#221]
## Describe the bug

Making changes to the session, then using `throw :abort` will lose changes to the session.

## To Reproduce

MVCE: https://github.com/joshleblanc/stimulus-reflex-test/tree/losing-session

Note it's the losing-session branch. 

Go to the New Foo page, add a bar, add anything to the bar textbox, then click "New Bar" again. The value you typed into the textbox will be lost.

If you remove `throw :abort` from the reflex, the value will be maintained.

## Expected behavior

The value should be maintained.

### StimulusReflex

- Gem: 3.2.1
- Node package: stimulus_reflex@^3.2.0-pre0

### External tools

- Ruby: 2.6.5
- Rails: 6.0.3
- Node: 13.5.0

### Browser

- Browser: chrome
- Version: 83.0.4103.61

**Comment by hopsoft** [comment]
This is definitely something we should be handling correctly. Thanks for the report.
