### ISSUE TITLE
Shorthand action notations corresponding to stimulus

### ISSUE THREAD

**Issue by namiwang** [hopsoft/stimulus_reflex#233]
# Feature Request

Stimulus has a wonderful list of `shorthand actions`. It's gonna be efficient if we could write `data-reflex='Post#update'` instead of `data-reflex='change->Post#update'` in stimulus_reflex as well.

## Additional context

Here's a list from stimulus

Element | Default Event
-- | --
a | click
button | click
form | submit
input | change
input type=submit | click
select | change
textarea | change

**Comment by leastbad** [comment]
Hi @namiwang thanks for the suggestion!

Long ago, this was in PR #12 and it was ultimately rejected by @hopsoft here: https://github.com/hopsoft/stimulus_reflex/pull/12#issuecomment-529136521

I've waffled on the shorthand actions, personally. I'm a huge fan of terse markup (I haven't fallen in love with TailwindCSS and #212) but I also think that there's value in being explicit about certain things, especially for newcomers.
