### ISSUE TITLE
data-reflex-attributes vs data-reflex-dataset

### ISSUE THREAD

**Issue by vpfaulkner** [hopsoft/stimulus_reflex#237]
# Bug Report

I think there is a bug in the docs. [Here](https://docs.stimulusreflex.com/reflexes#inheriting-data-attributes-from-parent-elements) they say to use `data-reflex-attributes="combined"` for data-attribute inheritance, but I think it should say `data-reflex-dataset="combined"`. See https://github.com/hopsoft/stimulus_reflex/blob/master/javascript/schema.js#L5.

## Describe the bug

Update the docs to say `data-reflex-dataset="combined"`

## To Reproduce

Try out the feature

## Expected behavior

Correct documentation

## Screenshots or reproduction

None

### StimulusReflex

- Gem: 3.2.2
- Node package: 3.2.2

### External tools

- Ruby: 2.6.4
- Rails: 6.0.3

### Browser

- Browser Chrome
- Version 83

**Comment by marcoroth** [comment]
Good catch, you are right @vpfaulkner. Thanks!

**Comment by leastbad** [comment]
Gracias!
