### ISSUE TITLE
Server signing salt

### ISSUE THREAD

**Issue by pjforde1978** [hopsoft/stimulus_reflex#24]
One thing I noticed that Phoenix LiveView has implemented is a signed salt to verify the authenticity of requests and prevent bad actors.

https://github.com/phoenixframework/phoenix_live_view/#installation

This *seems* like something handled by ActionCable, but if not, it's probably a good idea to consider something like this, given that many actions could trigger destructive changes via CRUD-like reflexes.

**Comment by hopsoft** [comment]
This definitely seems like a concern that is/should-be handled at a lower layer. i.e. `ActionCable`
