### ISSUE TITLE
ActiveStorage variants performance

### ISSUE THREAD

**Issue by matedemorphy** [hopsoft/stimulus_reflex#242]
hi, i'm developing an app wich implements images uploads. The thing is, that at the moment of show a variant of the images, is not working properly since returns an empty result of a query that it has results. I'm using the Pagy gem, and the content of one of the table's column are 200x200 images. When i try to navigate arround the table in the second or third next or prev click, it returns empty results, thats the problem. Thanks for your help.

This is part of the code:
https://gist.github.com/matedemorphy/b714b50596ca1c71f2ae5c3015d2e350

**Comment by julianrubisch** [comment]
hm... did you try lazy loading image variants via javascript?

also, it could be helpful if you gave us a little more context. for example, in your gist I cannot find the mentioned `variant` call...

by "empty results", do you mean that the active storage URL is empty, or it's not delivering images?

**Comment by matedemorphy** [comment]
@julianrubisch thanks for yout answer, what i did not mentioned is that is a multi tenant app, so i'm using the  gem. I've solved by switch the tenant inside the reflex method too. Apartment::Tenant.switch! tenant.
