### ISSUE TITLE
Error handling will fail if reflex is not defined

### ISSUE THREAD

**Issue by joshleblanc** [hopsoft/stimulus_reflex#253]
## Describe the bug

The error handling here: https://github.com/hopsoft/stimulus_reflex/blob/master/lib/stimulus_reflex/channel.rb#L36 will fail to give the user any useful error message if the reflex is not successfully defined here: https://github.com/hopsoft/stimulus_reflex/blob/master/lib/stimulus_reflex/channel.rb#L33

## To Reproduce

Steps to reproduce the behavior

## Expected behavior

There should be a helpful error message alerting the user that they are attempting to call a reflex that doesn't exist.

**Comment by leastbad** [comment]
This is true and needs to be fixed. We've had discussions about it before but here we are. My position is that an error catch should make no assumptions about an object in the rescue block being successfully created.
