### ISSUE TITLE
beforeUpdate/updateSuccess/updateError functions deprecated?

### ISSUE THREAD

**Issue by asadakbar** [hopsoft/stimulus_reflex#255]
Hi, I'm following along the chatter youtube tutorial and saw that the example controller mentions
```
  // beforeUpdate(element, reflex) {
  //  element.innerText = 'Updating...'
  // }

  // updateSuccess(element, reflex) {
  //   element.innerText = 'Updated Successfully.'
  // }

  // updateError(element, reflex, error) {
  //   console.error('updateError', error);
  //   element.innerText = 'Update Failed!'
  // 
```

But the documentation refers to lifecycle methods being in the vein of `beforeReflex`. Are those no longer used?

**Comment by leastbad** [comment]
Hi Asad!

You are confusing generic and custom lifecycle events.

If you have a kitten method, your controller will have a `beforeKitten` method. `beforeReflex` will fire for all methods.

**Comment by asadakbar** [comment]
@leastbad Got it. With the examples being `beforeUpdate`, it wasn't clear to me that `Update` referred to the name of a random method and could have been anything else. Maybe thats something that could be changed in the commented example code. I can submit a pr if that would be helpful.

**Comment by leastbad** [comment]
I agree! We'd love a PR for this.
