### ISSUE TITLE
Scoped register()?

### ISSUE THREAD

**Issue by pjforde1978** [hopsoft/stimulus_reflex#26]
One thing I learned from this [so-so conference talk](https://www.youtube.com/watch?v=9eOo8hSbMAc) is that LiveView allows you to scope your MorphDom target to arbitrary elements.

In theory, that means you could have multiple reflex "widgets" going at once on the same page. We already have controller scoped reflexes working (at least in my PR! **cough**) and it seems like we could pass that context to CableReady instead of assuming that we want to replace the whole body tag.

DHH got everyone obsessed with REST but there's nothing stopping devs from setting up actions that render arbitrary HTML for a widget with render(layout: false).

**Comment by hopsoft** [comment]
This is on the roadmap. I'm waiting for Rails 6.1 as I anticipate that partial page updates will be supported specifically with `ActionView::Component`. See this effort for some additional context. https://github.com/effkay/stimulus_reflex/commit/91f855ba2febc05bc376affa5e0e592866a2ba8b
