### ISSUE TITLE
Lifecycle hooks

### ISSUE THREAD

**Issue by matedemorphy** [hopsoft/stimulus_reflex#266]
Hi, my question it's about Lifecycle. In this gist https://gist.github.com/matedemorphy/94c6ad13b6aebd89862b5b14120c98df you could see the implementation of a cursor spinner wich should hide in `afterReflex()`, but sometimes this callback doesn't works. 

I have this line in config/initializers/session_store.rb

`Rails.application.config.session_store :cookie_store, key: _my_app, domain: lvh.me`, but then in development.rb

`config.session_store :cache_store`
`config.cache_store = :file_store, Rails.root.join(tmp, cache).to_s, { size: 320.megabytes }` it could some conflict there?

**Comment by hopsoft** [comment]
Did adding ids resolve this? Curious based on the conversation in Discord. https://discordapp.com/channels/629472241427415060/629472241427415062/731945448339931146

**Comment by matedemorphy** [comment]
@hopsoft Yes, solved!
