### ISSUE TITLE
First argument of type "object" in this.stimulate() will always be assigned to options.

### ISSUE THREAD

**Issue by shawnleong** [hopsoft/stimulus_reflex#278]
# Bug Report

## Describe the bug

The first argument of type "object" being passed into `this.stimulate()` will always be assigned to `const options`.
The check to see if an object is an options object will always return true... even if the option keys are not present in the object.

This results in data["args"] being an empty array because the first argument of type object is shifted and assigned to `options`. 

The corresponding server side reflex expects an argument but is not passed any will raise the following error
`wrong number of arguments (given [], expected [[:req, :params]], optional [])`

## To Reproduce

Steps to reproduce the behavior

1. Create a stimulus controller based reflex
2. Pass in an object as the first argument with any key that's not used for options
3. Stimulate

**For example**
Client side stimulus controller
```
// app/javascript/controllers/example_controller.js
var params = { example: "object" }
this.stimulate("ExampleReflex#action", params)
```

Specific issue
```
// stimulus_reflex/javascript/stimulus_reflex.js
...
const options = {}
if (
  args[0] &&                                            // true
  typeof args[0] == 'object' &&                         // true
  Object.keys(args[0]).filter(key =>
    ['attrs', 'selectors', 'reflexId'].includes(key)
  )                                                     // This returns an array even if key is not present, which in turn allows the conditional to eval true
) {
  const opts = args.shift()
  Object.keys(opts).forEach(o => (options[o] = opts[o]))
}
...
```

## Expected behavior

Argument of type 'object' should not be assigned to `options` if it does not have any of the keys `['attrs', 'selectors', 'reflexId']` 
```
// stimulus_reflex/javascript/stimulus_reflex.js
...
const options = {}
if (
  args[0] &&                                         
  typeof args[0] == 'object' &&                       
  Object.keys(args[0]).filter(key =>
    ['attrs', 'selectors', 'reflexId'].includes(key)
  )                                                       
  .includes(true)                // quick fix
) {
...
```

Update: Added a Pull Request #279 

## Screenshots or reproduction

![Screenshot from 2020-07-21 15-02-05](https://user-images.githubusercontent.com/17049613/88023287-5f579e80-cb63-11ea-9155-56e4d82b44f2.png)

### StimulusReflex

- Gem: [3.3.0.pre2]
- Node package: [3.3.0.pre2]

### External tools

- Ruby: [2.6.3]
- Rails: [6.0.0]

### Browser

- Browser [chrome, firefox]

**Comment by hopsoft** [comment]
Fixed by #279
