### ISSUE TITLE
Use set I18n.locale in Reflexes with Selector Morphs 

### ISSUE THREAD

**Issue by stebo** [hopsoft/stimulus_reflex#280]
When using the new Selector Morph functionality (which is awesome!, currently available in _3.3.0.pre2_) `ApplicationController.render` will not use any previous set I18n.locale (that might have been set in your ApplicationController) but instead only uses the default locale. 

```
class FollowReflex < StimulusReflex::Reflex
  def follow
    ...
    morph "#follow_form", ApplicationController.render(partial: "users/unfollow")
  end
```

Of course it is possible to manually set the locale for each`render` with accessing the current_user.locale or a locale set in the session and using `I18n.with_locale`, this is how I currently do it:

```
morph "#follow_form",
  I18n.with_locale(session[:locale]) { ApplicationController.render(partial: "users/follow") }
```

Is there any way to already accomplish that without always manually adding `I18n.with_locale`? I just would love to keep the code as clean and short as possible here. 

Thanks in advance and really love this project!

**Comment by leastbad** [comment]
Thanks for raising this issue - it's really interesting and frankly this is an example of why I love open source. I have an English-speaking lens and would likely have never considered this.

Here's what I'm thinking (out loud): what if we added a class method that allowed you to do something like this?

```ruby
class FollowReflex < StimulusReflex::Reflex
  locale session[:locale]
  def follow
    morph "#follow_form", ApplicationController.render(partial: "users/unfollow")
  end
end
```
and this would wrap the 2nd parameter so that it's the block argument of `I18n.with_locale(session[:locale])`

Does that make sense?

You could, in the interim, also experiment with it as something you could define as a function in the Reflex class. Something like:
```ruby
def with_locale
  I18n.with_locale(session[:locale]) { yield }
end
```
and that would let you do something like:

```ruby
class FollowReflex < StimulusReflex::Reflex
  def follow
    morph "#follow_form", with_locale(ApplicationController.render(partial: "users/unfollow"))
  end
end
```

There's also a trick I just added to the docs where you can specify:
```ruby
delegate :render, to: ApplicationController
```
at the top of your Reflex class and then you can call `render(partial)` instead of `ApplicationController.render(partial)`

Anyhow, if you could please try some of these ideas and report back, we'll then talk about how best to proceed wrt whether this is something that should be in the library, in the documentation, or what. Cool?

**Comment by stebo** [comment]
Thanks for the fast and awesome feedback, really appreciate it! 

I used your suggestions with an own function `def with_locale` as well as `delegate :render` (I put them in an extra `ApplicationReflex` that my other Reflexes inherit from) and this way my code for the render is not pretty nice and clean!

This ofc still feels a bit like a "workaround" and it would be best if StimulusReflex automatically could access & apply the standard Rails settings (e.g. an `I18n.locale`) as if one would call an `ApplicationController.render` from anywhere else within the application.

But I must admit I still don't get the technology behind all this enough to grasp if that would be possible at all - or if there always needs to be the session[: ... ] to share information...

Having a `locale` class method as you suggest, might work nice but is also not that much leaner than defining an own function for this - and on the other hand feels a bit like overkill for that specific use case maybe.

### Current objects

Another more "global" approach could be (if possible) to make the whole [Current object](https://api.rubyonrails.org/classes/ActiveSupport/CurrentAttributes.html) available within the Reflex, as this would be a perfect place to store things like Locale, Currency, and of course the User authorization as well.

In my application I have many partials using the Current object, as I think it's now the "Rails way" to do it - with `Current.user`, `Current.currency` or others. 
To make these partials work with StimulusReflex Selector Morphs I did

```ruby
class ApplicationReflex < StimulusReflex::Reflex
  delegate :current_user, to: :connection
  delegate :render, to: ApplicationController

  before_reflex do
    Current.user = current_user
  end
```
But ofc I cannot access  `Current.currency` now for example.

Maybe that could be a general approach as well, to have the Current object available in a Reflex, and then use it to store / share stuff - but again, not sure if technical possible at all.

**Comment by leastbad** [comment]
I'm glad that my `with_locale` method worked. TBH I wrote it sight-unseen, so I'm feeling a little proud right now. 😀 

Truth be told, this is about as far as I know how to take it without further input from @hopsoft who has worked a lot with the Current pattern in his projects. I'm still a `current_user` guy myself. Excited to learn new tricks.

**Comment by leastbad** [comment]
Hey, would you mind pasting a copy of your reflex(es) that make use of the `with_locale` stuff? I'm considering mentioning it in the documentation, at least until a more formal solution is available.

**Comment by stebo** [comment]
Of course! I am just pasting my whole `ApplicationReflex`, you can of course just select the `with_locale` stuff.

```ruby
# application_reflex.rb
class ApplicationReflex < StimulusReflex::Reflex
  delegate :current_user, to: :connection
  delegate :render, to: ApplicationController

  before_reflex do
    Current.user = current_user
  end

  def with_locale(&block)
    I18n.with_locale(session[:locale]) { yield }
  end
end
````

And than use in other reflexes like this
```ruby
# follow_reflex.rb
class FollowReflex < ApplicationReflex
  def follow
    @user = User.find(element.dataset[:user_id])
    Current.user.follow(@user)
    morph "#follow_form", with_locale { render(partial: "users/unfollow", locals: {user: @user}) }
  end
end
```

**Comment by leastbad** [comment]
You are a champion!

I'm going to work this into the Useful Patterns section of the docs, at least until something more official is on the horizon. Thanks for working through this with us.

**Comment by julianrubisch** [comment]
It would be beneficial to more thoroughly grok I18n. In https://github.com/julianrubisch/futurism/ I had a related issue that was solved by correctly merging in `env` from the connection when working with `ApplicationController.render`... I'm still running an ugly hack there including setting private instance variables... you can always also instantiate an `ApplicationController.renderer.new` with a new env which is what I'll probably end up doing: https://api.rubyonrails.org/classes/ActionController/Renderer.html#method-i-new

**Comment by leastbad** [comment]
I'm going to close this for now. Thanks to this thread, there's a pretty good writeup in the docs.

https://docs.stimulusreflex.com/patterns#internationalization
