### ISSUE TITLE
Lifecycle callbacks do not work

### ISSUE THREAD

**Issue by uurcank** [hopsoft/stimulus_reflex#281]
# Bug Report

None of the callbacks get triggered after a succesful reflex

## Expected behavior

afterReflex should trigger after every reflex 

```
afterReflex(element, reflex)  {
 console.log('callback works')
}

```
 
### StimulusReflex

3.3.0-pre2

### External tools

- Ruby: 2.7
- Rails: 6.0.0

### Browser

- Chrome
-  84.0.4147.89

**Comment by leastbad** [comment]
Hi! We're going to need a lot more context to troubleshoot this.

Could you please post a repo we can look at, or at least a gist with the html, js and reflex class in play?

Also: strongly suggest you join Discord if you haven't already! https://discord.gg/XveN625

**Comment by bbonamin** [comment]
did you add `StimulusReflex.register(this);` on `connect()?`
this works just fine for me:
```javascript
import { Controller } from "stimulus";
import StimulusReflex from "stimulus_reflex";

export default class extends Controller {
  static targets = ["loadingIndicator"];

  connect() {
    this._hideLoadingIndicator();
    StimulusReflex.register(this);
  }

  beforeReflex() {
    this._showLoadingIndicator();
  }

  afterReflex() {
    this._hideLoadingIndicator();
  }

  updateFilter(event) {
    this.stimulate("SearchTopbar#update_filter");
  }

  _showLoadingIndicator() {
    this.loadingIndicatorTarget.style["display"] = null;
  }

  _hideLoadingIndicator() {
    this.loadingIndicatorTarget.style["display"] = "none";
  }
}
```

**Comment by uurcank** [comment]
I have been testing on the application controller. 

```
import { Controller } from 'stimulus'
import StimulusReflex from 'stimulus_reflex'

/* This is your application's ApplicationController.
 * All StimulusReflex controllers should inherit from this class.
 *
 * Example:
 *
 *   import ApplicationController from './application_controller'
 *
 *   export default class extends ApplicationController { ... }
 *
 * Learn more at: https://docs.stimulusreflex.com
 */
export default class extends Controller {
  connect () {
    StimulusReflex.register(this)
  }

  /* Application wide lifecycle methods.
   * Use these methods to handle lifecycle concerns for the entire application.
   * Using the lifecycle is optional, so feel free to delete these stubs if you don't need them.
   *
   * Arguments:
   *
   *   element - the element that triggered the reflex
   *             may be different than the Stimulus controller's this.element
   *
   *   reflex - the name of the reflex e.g. "ExampleReflex#demo"
   *
   *   error - error message from the server
   */

  beforeReflex (element, reflex) {
    // document.body.classList.add('wait')
  }

  reflexSuccess (element, reflex, error) {
    // show success message etc...
  }

  reflexError (element, reflex, error) {
    // show error message etc...
  }

  afterReflex (element, reflex) {
     console.log('callback triggered;);
    }
}
```

**Comment by helphop** [comment]
My callbacks in the application_controller.js fire but callbacks in other stimulus controllers do not.

Example

example_controller.js

```
import { Controller } from 'stimulus'
import StimulusReflex from 'stimulus_reflex'
export default class extends Controller {

  connect() {
    StimulusReflex.register(this);
    console.log('connected');
  }

  beforeReflex(element, reflex) {
    console.log('hi');
  }
}
```

The form:

```
  <%= form_with(model: [notebook, page, paragraph], data: {reflex: "submit->Example#update", signed_id: paragraph.to_sgid.to_s}) do |form| %>
    <%= form.rich_text_area :content, class: 'mb-3' %>
    <%= form.submit "Save", class: 'btn btn-primary mr-2' %>
  <% end %>

```

No console messages are shown.

**Comment by leastbad** [comment]
What if you try this:

```html
  <%= form_with(model: [notebook, page, paragraph], data: {controller: "example", reflex: "submit->Example#update", signed_id: paragraph.to_sgid.to_s}) do |form| %>
    <%= form.rich_text_area :content, class: 'mb-3' %>
    <%= form.submit "Save", class: 'btn btn-primary mr-2' %>
  <% end %>
```

**Comment by helphop** [comment]
That works! Thank you.

**Comment by leastbad** [comment]
Awesome. Yeah, the controller has to be on an element in order to receive events.

**Comment by uurcank** [comment]
@leastbad  how about this one?

   ```
 document.addEventListener('stimulus-reflex:after', event => {
      console.log('after reflex')
    })
```

this does not work.

however before event works

```
 document.addEventListener('stimulus-reflex:before', event => {
      console.log('before reflex')
    })
```

**Comment by leastbad** [comment]
@uurcank I need more information.

1. What file does the above code live in?
2. Can you confirm that it is in a controller that has been bound to an element in your DOM via `data-reflex="mycontroller"`?

**Comment by uurcank** [comment]
@leastbad  i think it is an issue with transforming camel-case names

I have a controller called task_activity_controller.js

```
class TaskActivityReflex < ApplicationReflex
end
```

If I call it like this, callbacks don't work but reflex method does.

```
  <%= form_with(model: [notebook, page, paragraph], data: {controller: "task-activity", reflex: "submit->TaskActivity#update", signed_id: paragraph.to_sgid.to_s}) do |form| %>
    <%= form.rich_text_area :content, class: 'mb-3' %>
    <%= form.submit "Save", class: 'btn btn-primary mr-2' %>
  <% end %>
```

If I call like this, callbacks work but reflex does not.

```
  <%= form_with(model: [notebook, page, paragraph], data: {controller: "task-activity", reflex: "submit->task-activity#update", signed_id: paragraph.to_sgid.to_s}) do |form| %>
    <%= form.rich_text_area :content, class: 'mb-3' %>
    <%= form.submit "Save", class: 'btn btn-primary mr-2' %>
  <% end %>
```

I suppose it might be fixed in the lifecycle.js

https://github.com/hopsoft/stimulus_reflex/blob/522e793cc55cff8056a79787632115358dc254c2/javascript/lifecycle.js

**Comment by leastbad** [comment]
Okay, thanks and I will look into this ASAP.

Can you please verify that you are running v3.3.0-pre3 both Gem and NPM package?

**Comment by uurcank** [comment]
@leastbad  i am on 3.2 but the related code seems to be the same in both, unless I am missing something.

**Comment by uurcank** [comment]
@leastbad  my gem was  3.2 but npm was   "stimulus_reflex": "^3.3.0-pre1",

**Comment by uurcank** [comment]
I tested on 3.3.0-pre3, problem persists.

**Comment by leastbad** [comment]
Okay... so according to the issue ticket you said that you're running `v3.3.0-pre2` (which assumes you have both gem and npm running the **exact** same version). You commented 15 minutes ago that your client was running `3.3.0-pre1` which is, to be precise, not the same thing as `pre2`.

Meanwhile, we released an update (`pre3`) largely to address the concerns in this issue a week ago, and it seems like you're now back on `3.2`... which is it?

You can surely see how this is frustrating. For the record, we wouldn't tell people to make sure that their gem and npm package versions are sync if it didn't matter. Specifically, it matters a lot. It also invalidates any time I've spent troubleshooting your issue.

Can you please upgrade both the gem and the npm package to `v3.3.0-pre3` and test your application again? It would help us a great deal.

**Comment by leastbad** [comment]
Okay, thank you. I know I sound frustrated, but your efforts mean a lot to me and the team.

We are working on a fix.

**Comment by uurcank** [comment]
@leastbad no worries. you are definitely right, I should have checked recent releases before opening the issue.  

I have just tested with 3.3.0-pre3, problem seems to persists. gem and npm is both 3.3.0-pre3

**Comment by leastbad** [comment]
@uurcank if you are driven, motivated and keen, you can point your Gemfile and package.json to the commit attached to #299 and hopefully you will feel as though visited by angels.

**Comment by uurcank** [comment]
@leastbad  how can i point package.json to this commit? 

in gem file i guess i can pull your after_reflex branch, but not familiar with package.json

**Comment by leastbad** [comment]
That *looks* right. When you say it is not working, could you be more specific? What happens when you run `yarn install` after changing your `package.json`?

**Comment by uurcank** [comment]
@leastbad  i get import errors in webpack when I start rails server. 

it fails to import stimulus_reflex after installing.

**Comment by uurcank** [comment]
yarn install succeeds with no issues, webpack raises errors

**Comment by leastbad** [comment]
Did you restart `webpack-dev-server`? What errors is it raising?

I can't see what you see, friend.

**Comment by uurcank** [comment]
@leastbad by the way, callbacks in application_controller should also work right? regardless of whether there is a callback function in controller. 

From what I see these callbacks never get triggered as well.

```
// application_controller.js

beforeReflex (element, reflex) {
    // document.body.classList.add('wait')
  }

  reflexSuccess (element, reflex, error) {
      console.log('reflex success')
    // show success message etc...
  }

  reflexError (element, reflex, error) {
    // show error message etc...
  }

  afterReflex (element, reflex) {
    console.log('after reflex')
  }
```

**Comment by uurcank** [comment]
here are errors from webpack 

```
ERROR in ./app/javascript/controllers/task_activity_controller.js
Module not found: Error: Can't resolve 'stimulus_reflex' in '/mnt/c/Users/Documents/testapp/app/javascript/cont
rollers'
resolve 'stimulus_reflex' in '/mnt/c/Users/Documents/testapp/app/javascript/controllers'
  Parsed request is a module
  using description file: /mnt/c/Users/Documents/testapp/package.json (relative path: ./app/javascript/controll
ers)
```

**Comment by leastbad** [comment]
Yes, correct. And verified today.

I don't know how to help you further without an MVCE I'm afraid. What you are describing works fine on my machine and so far as I know, everyone else's. The post-Reflex callbacks had a very real timing issue that should be mitigated by #299 but if you're having trouble with `beforeReflex` then something is seriously wrong.

As for the webpack error, it appears to be looking for stimulus_reflex in your project's `javascript/controllers` folder. I don't know why it would do that. Again, without an MVCE I'm just guessing about how you have your project set up. What you're showing is **not** what we see.

If you want, you can clone my test harness for #299 here: https://github.com/leastbad/stimulus_reflex_harness/tree/after_reflex

I have it set up with a local gem bundle and yarn link. I understand if that's a bridge too far, but unless you give me something I can reproduce locally, we're kind of stuck unless there's something else you can spot in your setup.

**Comment by uurcank** [comment]
@leastbad  ok found it.  for npm i just needed to import the javascript folder in the repository. Importing the branch installs the ruby gem to node_modules

I can confirm that after_reflex works 👍

**Comment by uurcank** [comment]
@leastbad   there may also be an issue with Turbolinks.

after_reflex works on initial page load, but after I change a page, only before_reflex works. 

is this something you can test on your end?

**Comment by leastbad** [comment]
Turbolinks should work just fine. Can you be more clear about what project you're seeing this behaviour with?

There isn't a good reason why Turbolinks would make afterReflex stop working...

**Comment by uurcank** [comment]
@leastbad  In a modal window, I call a reflex action upon ajax:success event.

 After I switch the page, and open the same modal from that page, after_reflex do not get called. before_reflex is always called. So I thought perhaps Turbolinks may be intervening. Not sure what else would do that after page change.

I can try to create an example sometime this week but should you choose to try yourself. here are steps to recreate this issue:

- create two pages
- create a modal window, which contains a form that is submitted via Ajax. 
- Editor controller submits the form on click
- reflex called upon ajax:success and updates values on the page
- then switch the page and open the same model from that page.

```
<%= form_with(model: task,
    data: {
      controller: 'editor',
      target: 'editor.form',
      reflex:  'ajax:success->Editor#refresh' : 
    },
    remote: true
  ) do |form|
%>
<%= form.submit, data: {action: 'click->editor#submit'} %>
<% end %>

// editor_controller

  submit() {
    event.preventDefault()
    Rails.fire(this.formTarget, 'submit')
  }

```

**Comment by uurcank** [comment]
I also tried steps [mentioned here ](https://github.com/hopsoft/stimulus_reflex/issues/161)but did not make any change

**Comment by leastbad** [comment]
I'm not able to go on fishing expeditions, I'm sorry. MVCE or bust. There's just too many variables in how your project might be set up.

Feel free to fork the harness project and use it to jumpstart your exploration. It doesn't have Turbolinks installed. If you install Turbolinks into the project such that you can turn it on/off, you'll quickly be able to isolate TL as the cause or a red herring.

**Comment by uurcank** [comment]
on that note we can close this issue I think. This is likely a different problem anyway. 

Callbacks work with the change you have added. 👍  

Perhaps we can revisit modals + ajax later on as more people provide feedback for it.

**Comment by leastbad** [comment]
Thanks for sticking with this one, Ugurcan. It motivated me to find a better solution.
