### ISSUE TITLE
Reflex ignores turbolinks cached pages

### ISSUE THREAD

**Issue by uurcank** [hopsoft/stimulus_reflex#288]
# Bug Report

We have a multi-tenant app that works with cookies. When you change an account, it sets "current_account" via session cookies.

## Describe the bug

After you switch account, and take an action that triggers a reflex, Stimulus-Reflex renders the page for the previous account, not current_account. 

Turbolinks is also enabled in this app. What is probably happening is that Turbolinks caches the page that user navigates to and Reflex renders the very first page upon action, not the turbolinks cached "current" page.

Does reflex not work well with Turbolinks?  What is a good way to prevent this happening?
 
### StimulusReflex

- Node package: 3.2.2

### External tools

- Ruby: 2.7
- Rails: 6.0.0

**Comment by leastbad** [comment]
Hi @uurcank! I'm sorry that you're stuck.

SR is explicitly designed to work great with Turbolinks. What we don't support is cookie-based session storage:

https://docs.stimulusreflex.com/setup#command-line-install

https://docs.stimulusreflex.com/persistence#the-rails-session-object

Are you able to switch to a server-side session management solution?

**Comment by uurcank** [comment]
@leastbad  I think i am confused. What do you guys mean that it does not support cookie-based storage? Once session object is updated, it should not matter for reflex and it should only update the changed portion of the DOM.

In this case, it does a full-render and replaces the page with the cached one. Even after the session object is updated with a full page load via controller action.

**Comment by leastbad** [comment]
Hi @uurcank. I'm not sure what you want me to say. I appreciate that you feel strongly that cookie-based storage should work, and I assure you that we didn't explicitly warn people that it wouldn't work multiple times in the documentation just to ruin your day.

If you're interesting in understanding more about how SR works with sessions behind the scenes, check out https://github.com/hopsoft/stimulus_reflex/blob/7c80cc8adac55af5413a0bc8379ab251aeae5b0e/lib/stimulus_reflex/reflex.rb#L64 and https://github.com/hopsoft/stimulus_reflex/blob/7c80cc8adac55af5413a0bc8379ab251aeae5b0e/lib/stimulus_reflex/channel.rb#L82 so you can start to see the lengths we go to so our API users can enjoy a (mostly) seamless experience.

Could you please temporarily disable Turbolinks and test to see if this behaviour changes?

**Comment by uurcank** [comment]
@leastbad I am just asking to understand how it works. Sorry if it sounds angry :) 

I checked the code but could not make the connection to cookie-based storage. Can you please point me to the lines why cookie-based storage would affect an action cable process, which is injecting or rendering HTML in this case? How does it work and why would cookie bases storage is a problem for reflex?

I will test without Turbolinks and post here later today.

**Comment by leastbad** [comment]
What I've been trying to show you, broadly, is that you keep using the word "should", as though you can declare it true. How I wish it was so!

We have to actively synchronize the session state and instance variables between the bubble universe we create inside of the Reflex context and the rest of the application. @hopsoft is the one who has taken the lead on this development, and perhaps he can provide some additional context. In the meantime, you can follow the progression:

https://github.com/hopsoft/stimulus_reflex/pull/124
https://github.com/hopsoft/stimulus_reflex/pull/131
https://github.com/hopsoft/stimulus_reflex/pull/222

**Comment by hopsoft** [comment]
@uurcank The challenge is rooted in the fact that the web socket is initialized once and is persisted across Turbolinks page visits. The initial HTTP web request that is upgraded to a socket connection sends over the cookie headers on that initial connection request. The state stored on the established socket is persistent and doesn't receive cookie updates, so if the multi-tenant app is tracking the current tenant via cookie then the web socket is unaware that you've switched tenants. 

One possible solution would be to force ActionCable to reconnect when the tenant changes.

Note that we are working toward supporting stateful cookie management on the socket, but don't yet have an ETA on when it might ship.

**Comment by leastbad** [comment]
`ActionCable.server.remote_connections.where(current_user: User.find(1)).disconnect`

**Comment by uurcank** [comment]
@leastbad  the reason I keep saying it "should" is because the documentation presents Reflex as an alternative to javascript frameworks for compex UI, like React. So one would expect that it will work out of the box with any Rails app with zero structural change. If it does not work out of the box, it will not become a strong alternative. 

That being said, I also do not think there is any reason why it would not work with cookie-based authentication. Declaring it unfavorable in the documentation conflicts with the whole purpose of Reflex ( of that I have read in the documentation).  It will be better to explain the reasoning and leave it open-ended. That's the whole point of open-source development right? Library should not be opinionated in that regard, so are the maintainers.  

@hopsoft thanks for the explanation. I did not know that web socket is initialized once. I was just assuming when turbolinks is disabled on a link, it would rebuild the websocket. But it doesn't.

Unless you refresh the page from browser, web socket persists. None of these work:

```
<a data-turbolinks="false">Change Account</a>
<a target="_parent">Change Account</a>
<a target="_top">Change Account</a>
```

Ensuring full page load with turbo links meta tag works, it may be useful for a "tenant switch" page or similar:

`<meta name="turbolinks-visit-control" content="reload">`

Forcing action cable to reconnect also works:

```ruby
def switch
  # Force action cable to reconnect
  ActionCable.server.remote_connections.where(current_user: User.find(current_user.id)).disconnect

   session[:account_id] = @account.id
   redirect_to root_path
end
```

Perhaps we can mention this in the docs and it may just be more than enough.

**Comment by hopsoft** [comment]
Closed given that we have a work around and cookie support is on the roadmap.
