### ISSUE TITLE
Update client controller template comments

### ISSUE THREAD

**Issue by leastbad** [hopsoft/stimulus_reflex#298]
# Feature Request

Both of the templates in `lib/generators/templates/app/javascript/controllers/` have some minor issues that could be easily addressed.

## Describe the solution you'd like

- on line 29 of the `application_controller.js.tt` it shows `ExampleReflex#demo` but this could be simplified to `Example#demo`
- same thing happens on line 20 of the generic template
- in the generic template, we should demonstrate that if they want to append and not just override methods present in controller, you have to call `super`. This is especially important for `connect`. It's a small bit of documentation that will save many headaches! So...
- add a `connect` example to the generic file eg.
```js
connect () {
  super.connect()
  // add your code here
}
```
- in the application controller template, re-word so that it's more clear and explicit: "these are event handlers for every reflex, for every controller that inherits from it"
- in the generic template, let's change reflex name from `update` to something more obviously specific like `dance` so that we can minimize the number of folks learning the framework who assume that these conceptually map to restful verbs
- let's point out that the controller has to be put on an elements with `data-reflex` for the callbacks to fire

There could be more! But these templates are an important part of our API and an early step in how people learn. If they are ambiguous, they will confuse people.

**Comment by pinzonjulian** [comment]
I'll pick it up :) I'll post a PR this week

**Comment by leastbad** [comment]
Hey Julian, how's this coming along?
