### ISSUE TITLE
self-referential data-reflex-root

### ISSUE THREAD

**Issue by scottbarrow** [hopsoft/stimulus_reflex#301]
# Feature Request

## Is your feature request related to a problem?
No, Enhancement suggestion

As a developer I would like the ability to succinctly specify a data-reflex-root element on a page and reference the element it's a property of (self referential)

## Describe the solution you'd like
`<div data-reflex-root>...</div> `

Pie in the sky idea - element to be rendered with a generated unique data attribute e.g. 

`<div data-reflex-root>...</div> ` generates something like
`<div data-reflex-root="[data-morph-id='d733f329332e4e248e71dd94556a18e6']" data-morph-id="d733f329332e4e248e71dd94556a18e6">...</div> `

## Additional context

current solution
`<div id='some_id' data-reflex-root='#some_id'>`

**Comment by leastbad** [comment]
Hey Scott, this looks interesting but I don't currently get the big picture. Could you talk about why this is useful to you? What problem is it solving, or behaviour is it replacing? No skepticism, I just don't currently know if I could explain to someone what scenario this is intended for.

**Comment by scottbarrow** [comment]
Sure, Im currently using `<div id='some_id' data-reflex-root='#some_id'>` which allows the morph to use the `#some_id` div as its selector. 
This seems a much better way of doing morph selectors from within the reflex, as the element I'm rendering back sometimes requires state or is otherwise not useable in the reflex.

The suggestion above is simply to have the ability to do this with a single data-attribute data-reflex-root with no value, in which case it would fallback to adding a data-id on the current element and using that as its reflex-root target for the selector.

**Comment by leastbad** [comment]
So if I understand... you're saying that specifying `data-reflex-root` without a value would trigger a behaviour where a uuid or similar would be generated and dynamically assigned to the element as an `id` attribute as part of the post-load/post-morph loop.

Why not just render an id inside of your view template before it goes to the client at all? I am afraid I don't currently get what problem the is solving, or when I'd use it. I want to understand badly, though! So if you have more examples, I'm listening.

That all said, changing the DOM after the page loads outside of the context of a morph isn't really something we do, and I'm not sure that you're convincing me that we should as it stands. If I understand correctly, this would introduce a whole layer of complexity that doesn't currently exist when you could just render an ID in your template.

**Comment by scottbarrow** [comment]
Its more of a convenience, its currently possible by providing your own id and using that in the data-reflex-root, however I presumed that since there is some dom manipulation happening by SR already e.g. nothing morphs/re-renders `click->stimulus-reflex#__perform` that it would be reasonable to expect it can add uuids. 

This would also work towards solving issues people are experiencing where an id or unique attribute is missing from the element causing the element to not be replaced

**Comment by leastbad** [comment]
I have to be honest and say that I'm not feeling this idea. You are correct that `data-reflex` gets mapped to the generic `stimulus-reflex` controller, but that's a core aspect of how the library works. There's no scenario where someone is supposed to manually set that controller, whereas setting an id is definitely something the developer is used to doing. The issue there is that every time the page renders, it'll end up with a new id and that is going to blow up the whole targeting process.

Meanwhile, it's clear that you can already do what you need to do with standard templating.

I love adding convenience methods to the library, but this is a bridge too far given the issues I outlined.

Please keep the ideas coming.

**Comment by sanchez2210** [comment]
I came looking for this issue because I had the same idea. @leastbad given your answers I understand that probably it's not a good fit for the library but maybe a small section in the docs would point newcomers in the right direction.

**Comment by leastbad** [comment]
@sanchez2210 thanks for the note, Luis!

Do you have any suggestions on what should be added, exactly? I have a work-in-progress section on anti-patterns that I suppose I could finally finish up, but I want to make sure that I understand exactly what you're suggesting.

Do you have any questions about what Scott was proposing, and why we passed on the concept?
