### ISSUE TITLE
IE11 Support: "crypto" is undefined

### ISSUE THREAD

**Issue by chooselife22** [hopsoft/stimulus_reflex#308]
# Bug Report

Window.crypto is undefined in Internet Explorer 11.

```
ReferenceError: "crypto" is undefined [object Object]
```
## Describe the bug

https://github.com/hopsoft/stimulus_reflex/blob/691dca45eb6d119a467d3efeb4fac11e0e230321/javascript/utils.js#L7  

from:
https://developer.mozilla.org/en-US/docs/Web/API/Window/crypto
```
var cryptoObj = window.crypto || window.msCrypto; // for IE 11
```
is the possible fix.

something like the following would work
![image](https://user-images.githubusercontent.com/5214867/93346585-6d106400-f834-11ea-9a1c-71dccf64d2c2.png)

## Screenshots or reproduction

open your app with IE11

### StimulusReflex

- Gem: 3.3.0.pre3
- Node package: 3.3.0-pre3

### Browser

- Browser Internet Explorer
- Version 11.1082.18362.0

**Comment by chooselife22** [comment]
any plans on supporting the ie11 crypto?

**Comment by leastbad** [comment]
Hi Andy, if this would make your life easier, please prepare a PR and I'll do my very best to get it included in the next major release (coming out on Tuesday). This seems pretty constrained and hopefully, harmless.

**Comment by chooselife22** [comment]
Hi leastbad, i prepared the PR for this issue. I tested it locally and the msCrypto object is used now in IE11. So the uuid function ist working.
