### ISSUE TITLE
Client side call-backs?

### ISSUE THREAD

**Issue by pjforde1978** [hopsoft/stimulus_reflex#34]
I saw the closed issue around server-side callbacks, but I'm surprised nothing has been discussed around client callbacks.

In the todomvc sample, when you click on a todo item to initiate an edit there's no way to set the typing focus on the input that is inserted. You effectively have to click twice; I did try to suppress the autofocus attribute on the create new todo textbox, as I was concerned that having two autofocus textboxes would conflict. Unfortunately, even if the todo you clicked on is the only autofocus element, the browser doesn't seem to take action on it after it's been dynamically inserted.

This suggests that there should be a simple way to specify a callback to handle the sorts of visual effects that make no sense or are impossible to render in a template.

I feel pretty strongly that sending arbitrary JS to execute via websockets is almost certainly a major attack vector, and then haven't we just re-invented RJS? Let's not go there.

That means, to me at least, that it would be nice to be able to do two things:

I would love to be able to async/await a JS call to this.stimulate() in the controller for explicit reflex calls. And I would love to be able to specify a data-callback attribute for declarative reflexes that would execute a controller method with the element passed as a parameter.

This means that element.focus() is easily possible, as is those sexy, sexy yellow pulse glow effects that were all the rage when Basecamp came out in 2004. Gosh, don't you just miss Prototype sometimes? ;)

**Comment by pjforde1978** [comment]
I just blinked and realized that you have a config.focusSelector switch in cable_ready.

https://github.com/hopsoft/cable_ready/blob/561e5cee7e9bff1ea313d73b74d833c29622eb27/javascript/cable_ready.js#L29

I mean, this doesn't cover the general notion of callbacks but I'm impressed at how you anticipated this before I was even aware of the project. :1st_place_medal:

**Comment by hopsoft** [comment]
Latest now supports this feature. https://docs.stimulusreflex.com/lifecycle
