### ISSUE TITLE
Console exception when reflex does not update a page that didn't trigger the reflex

### ISSUE THREAD

**Issue by rockhymas** [hopsoft/stimulus_reflex#363]
# Bug Report

Using a simple `morph :nothing` reflex action causes pages that did not trigger the reflex to have a console error.

## Describe the bug

Create a reflex that specifies `morph :nothing`. Open the same page in two tabs. Trigger the reflex. The tab in which it isn't triggered now has a console error:
```
stimulus_reflex.module.js:522 Uncaught TypeError: Cannot read property 'promise' of undefined
    at HTMLDocument.<anonymous> (stimulus_reflex.module.js:522)
    at dispatch (cable_ready.js:83)
    at Object.dispatchEvent (cable_ready.js:156)
    at Object.perform (cable_ready.js:349)
    at Subscription.received (stimulus_reflex.module.js:291)
    at action_cable.js:536
    at Array.map (<anonymous>)
    at Subscriptions.notify (action_cable.js:535)
    at Connection.message (action_cable.js:369)
```

## To Reproduce

See above

## Expected behavior

No console errors

## Screenshots or reproduction

Repro at https://github.com/rockhymas/srtest

### StimulusReflex

- Gem: 3.4.0.pre3
- Node package: 3.4.0-pre3

### External tools

- Ruby: [e.g. 2.6.4]
- Rails: [e.g. 6.0.0]
- Node: [e.g. 12.4.0]

### Browser

- Browser Chrome
- Version latest

**Comment by leastbad** [comment]
Thanks for noticing this, Rock. I'm looking into it this morning.

**Comment by leastbad** [comment]
One thing that is interesting/troubling is that it happens regardless of whether SR is in isolation mode or not.

I've also verified that the issue manifests on master.

**Comment by rockhymas** [comment]
It looks in part, like this is happening because there is a lifecycle event we want to fire for `nothing` morphs, i.e. `stimulus-reflex:nothing` and `reflexNothing`. That's not documented anywhere, but maybe some people are using it, though I can't imagine why they would. It seems like the fix here is to bail out of the handler for `stimulus-reflex:server-message` event when `subject === 'nothing'`. And do it before this line: https://github.com/hopsoft/stimulus_reflex/blob/master/javascript/stimulus_reflex.js#L501.

**Comment by leastbad** [comment]
@rockhymas if you could please test #368 ASAP I'd hugely appreciate it

**Comment by rockhymas** [comment]
Tested in my simple repro project, all good. Tested in the project I'm working on and I'm seeing another issue with nothing morphs.
```
stimulus_reflex.module.js:304 Uncaught TypeError: Cannot set property 'reflexController' of null
    at Subscription.received (stimulus_reflex.module.js:304)
    at action_cable.js:536
    at Array.map (<anonymous>)
    at Subscriptions.notify (action_cable.js:535)
    at Connection.message (action_cable.js:369)
```
It's happening at https://github.com/hopsoft/stimulus_reflex/blob/master/javascript/stimulus_reflex.js#L85 because `element` is null. I'll try to work up a simpler repro for it.

**Comment by leastbad** [comment]
That's a new one. Can you please confirm that you're not modifying the DOM after initiating the Reflex operation?

If you look at the server log, you can pick out the XPath value. Can you eyeball it and compare it to your app's DOM, make sure that the XPath resolves to the DOM element that initiated the Reflex? (That'll be the element with the `stimulus-reflex` controller, if there isn't one.)

**Comment by leastbad** [comment]
```js
const xPathToElement = xpath => {
  return document.evaluate(
    xpath,
    document,
    null,
    XPathResult.FIRST_ORDERED_NODE_TYPE,
    null
  ).singleNodeValue
}
```
You can use this function to take the XPath query and resolve it to a DOM element.

**Comment by rockhymas** [comment]
Yeah, the reflex sends a cableready message to delete the containing element (like deleting a todo in a list).

**Comment by leastbad** [comment]
Okay, well, there's your answer - you're deleting the elements before SR is done with them. That's not how the tool was designed to be used.

What I (strongly) suggest is that you use the afterReflex or after[Action] callback of the controller to `remove` the element after SR resolves the promise.

I'm going to close and merge, because the problem defined in this ticket has been resolved. Thanks for reporting and good luck with your app.

**Comment by rockhymas** [comment]
Cool, thanks for the pointers, and the original fix.
