### ISSUE TITLE
Multiple reflex submissions can lead to unexpected behaviour. 

### ISSUE THREAD

**Issue by jonathan-s** [hopsoft/stimulus_reflex#391]
# Feature Request
Not sure if I'd classify this as feature request or a bug. Either way. 

You can see the behaviour in the book search in the stimulus reflex expo. If you start to write something, stop for 200ms, then continue to write it will send two reflex submissions. All well and good so far. Because, the api endpoint is slow we have a loader. So after the first submission we start to see the spinner, the spinner continues after we sent the second submission. Then we get the results from the first submission and the spinner stops. A few moments later we get the results from the second submission. 

The result is that you think you got the right results when you get the update from the first submission. Then you get surprised when the dom updates again. 

So the feature idea here is: Perhaps it might be a good idea to purposefully cancel dom updates if that update is out of date and there is a newer submission that is more valid?

Or perhaps there is a better way to solve this problem?

**Comment by leastbad** [comment]
I believe that we already do a huge amount to ensure successful concurrency; see the new `finalize` stage.

At some point, after documentation and support, the developer must use the tools we give them and design their interactions properly.

**Comment by jonathan-s** [comment]
I'll have a look at the finalize stage!

**Comment by marcoroth** [comment]
Wouldn't that be solved with Nate's `debounced` library?

https://github.com/hopsoft/debounced

**Comment by jonathan-s** [comment]
Not really. The case I was trying to describe is that the user enters something two or more times and each time the debounce is short enough that it triggers a reflex and the reflex response is long enough that several dom updates are triggered. 

Though given a long reflex responses, the correct answer perhaps is re-designing the application so that subsequent requests are not triggered in that way :).
