### ISSUE TITLE
Install StandardJS linter

### ISSUE THREAD

**Issue by pjforde1978** [hopsoft/stimulus_reflex#40]
After much blinking and head-desking, I finally figured out the linting situation. It wasn't what was happening... it was what isn't happening.

I learned about StandardRB through the actions set up on this project. Not as far along, but promising and I used a [post-save hook](https://github.com/emeraldwalk/vscode-runonsave) to set it up to run in VSCode because StandardRB not available as an extension yet. `bundle exec standardrb --fix $(file)` for great success.

However, I've been thoroughly flummoxed by the JS lint situation, because StandardJS is so opinionated about (no) semi-colons. What I failed to grok until just now is that my brain assumed two incorrect things: that Prettier only tackled column-width and line-breaking, and that we had StandardJS set up in our post-commit and post-pull-request callbacks on GH.

I was wrong about Prettier - it inserts "missing" semi-colons and, well, I wish you could see my face the moment I realized that when GH's Actions interface said "Run Standard Lints" it meant only StandardRB.

:face_with_head_bandage:

[Javascript Standard](https://github.com/standard/standard) is a thing of beauty. [I find] Ruby code lends itself to readability, but JS's obsession with using nested object notation (it used to be far, far worse with nested anonymous function hell) makes the Prettier + Standard combo the first thing I set up in any JS project. There are many VS Code plugins; I recommend [Prettier-Standard](https://github.com/numso/prettier-standard-vscode).

Anyhow: can we please, please, pretty please set up StandardJS to run after Prettier? This will, predictably, solve the semi-colon thing.

**Comment by andrewmcodes** [comment]
@pjforde1978 you can use auto formatting with standardrb using the ruby extension FYI! See [here](https://github.com/rubyide/vscode-ruby/blob/master/docs/linting.md) for more info.

**Comment by andrewmcodes** [comment]
You can also set a workspace specific settings file in vscode to use prettier instead of prettier-standard. Happy to elaborate or walk you through how I do this.

**Comment by hopsoft** [comment]
We've moved to zero config prettier-standard. https://github.com/sheerun/prettier-standard
