### ISSUE TITLE
StimulusReflex (3.4.0.pre9) was unable to find an element 

### ISSUE THREAD

**Issue by jonatassalgado** [hopsoft/stimulus_reflex#406]
## Describe the bug

It seems like stimulus_reflex return only `key `attribute whitout data ("`data-key`"), so after in `findElement `method an query for element return no value.

They has unique key in a list os elements, I had test with id attribute also. I tested with _3.4.0.pre8_, same error (and `dispatchEvent`, after morph, to active lifecycle events not working).

This error occur after I update gem and js package from _3.3.0_

## To Reproduce

I simplify the names, but the behaviour is the same. In js files, I try to use `finalize` lifecycle event without success.

```
# components/event_component.html.erb
<%= component_controller do %>
	<%= reflex_tag :like, :div do %>
		Like
	<% end %>
<% end %>
```

```
# components/event_component.rb
class EventComponent < ViewComponentReflex::Component
    with_collection_parameter :event

  def initialize(event:, user:, parent_key: nil, open_in_sidebar: false)
      @event       = event
      @user         = user
  end

   def like
       @user.like! @event
   end

   def collection_key
       @event.id
   end
end
```

## Screenshots or reproduction
![](https://i.stack.imgur.com/sjv3Q.png)

  

### StimulusReflex

- Gem: 3.4.0.pre9
- Node package: 3.4.0.pre9

### External tools
- ViewComponentReflex 3.0.0
- Ruby: 2.6.3
- Rails: 6.0
- Node: v12.20.0

**Comment by joshleblanc** [comment]
This looks like a view_component_reflex issue. 

In any case, when rendering a collection of components with VCR, you'll want to provide a collection_key in your component, as described in the readme. 

https://github.com/joshleblanc/view_component_reflex#collections|

Failing that, please open an issue over there with an MVCE, and I'll take a peek

**Comment by jonatassalgado** [comment]
I started to perform the upgrade with more attention now, I believe I made a mess with the dependencies (gems/packages) and some custom code. When I get the latest version of stimulus_reflex and if the same error occurs I will reopen the issue. For now I will leave it closed until I confirm. Thanks for your attention @joshleblanc !
