### ISSUE TITLE
cable_ready method in Reflex class should support custom operations

### ISSUE THREAD

**Issue by leastbad** [hopsoft/stimulus_reflex#419]
Currently, the CableReadyChannels class does not recognize [operations created by the developer](https://cableready.stimulusreflex.com/customization#custom-operations).

I have devised a temporary workaround until a transparent solution can be locked down:

Let's say that you want to use your custom `jazz_hands` method in your Reflex class. You must add this to your Reflex action before you attempt to enqueue the custom operation:

```rb
cable_ready.instance_eval do
  define_singleton_method(:jazz_hands) do |options = {}|
    CableReady::Channels.instance[@stream_name].operations[:jazz_hands] << options
    self
  end
end
```

You should now be able to do this:

```rb
cable_ready.jazz_hands(thumbs: 2).broadcast
```

This assumes that you've defined a custom operation on the client as per usual:

```js
import CableReady from 'cable_ready'

CableReady.DOMOperations['jazzHands'] = operation => {
  console.log('Jazz hands!', operation)
}
```

**Comment by marcoroth** [comment]
This should be solved via #421.
