### ISSUE TITLE
dispatchEvent before morph in reflex actions

### ISSUE THREAD

**Issue by jonatassalgado** [hopsoft/stimulus_reflex#428]
# Bug Report

## Describe the bug

`dispatchEvent` before `morph` mostly for same reflex in sequence (or not). This occured after I upgraded from 3.3.0 version. I adjust stimulus `targets` to new implementation and remove code as described here in [setup#upgrading-to-v-3-4-0](https://docs.stimulusreflex.com/hello-world/setup#upgrading-to-v-3-4-0)

## Expected behavior

`dispatchEvent` after `morph ` (always?)

## Screenshots or reproduction
The last response is in correct way (`morph `before `dispacthEvent`).
![image](https://user-images.githubusercontent.com/9335343/104525258-822cb200-55de-11eb-82ac-43c43395459e.png)

But when the response is in correct way, I get other errors (I guess this is about view_component_reflex, even me using #id) just to complement this unexpected behaviour above. 
![image](https://user-images.githubusercontent.com/9335343/104525669-6a096280-55df-11eb-8b5c-b080a263aaae.png)

All this errors not exist in the previous version. Just in very rare occasions the `dispatchEvent` is triggered before `morph` only in production environment.

### StimulusReflex

- Gem: 3.4.0
- Node package: 3.4.0

### External tools

- Ruby: 2.6.3
- Rails: 6.0
- view_component 2.23.2
- view_component_reflex: 3.1.2
- stimulus: 2.0.0

**Comment by leastbad** [comment]
Hi there! I'm sorry you're having troubles. Could you please prepare an MVCE from the harness project linked in the SR readme so that we can clone, run and fix the issue on our local machine?

We need to be able to interact with code that is breaking to be able to do more than guess or make general suggestions - and have no doubt, we really want to help you fix this.

**Comment by leastbad** [comment]
Just let me know when it's ready. 💙

**Comment by jonatassalgado** [comment]
@leastbad It is a conflict with view_component_reflex and my application 😞 , I removed it in the application (I was testing it with new features) and everything worked perfectly. I will close this issue here and I will perform MVCE in view_component_reflex repository. 

Grateful for the attention! You from the stimulus community (reflex, view_component_reflex) are doing an excellent job for the Rails/Web community 😄

**Comment by leastbad** [comment]
Thanks John! Just let us know if something else comes up.
