### ISSUE TITLE
Installer can insert session_store config in wrong place

### ISSUE THREAD

**Issue by jonsgreen** [hopsoft/stimulus_reflex#429]
# Bug Report

## Describe the bug

The install rake task currently makes a [hard coded assumption](https://github.com/hopsoft/stimulus_reflex/blob/master/lib/tasks/stimulus_reflex/install.rake#L54) about where to add a line in the development.rb config. If however someone has altered that file (e.g. using `Style/FrozenStringLiteralComment` with rubocop which adds magic statement `# frozen_string_literal: true` to config files) then the line ends up outside the `Rails.application.configure` block, installation does not fully complete and the app will no longer start due to this error: 

```sh
undefined local variable or method `config' for main:Object
```

This is a pretty minor issue but could cause confusion and a bad first experience with the gem. 

## To Reproduce

Add `# frozen_string_literal: true` to top of `config/environments/development.rb` and then run `rails stimulus_reflex:install` on a new rails app. 

## Expected behavior

The `config.session_store :cache_store` line should get added within the configure block. 

### StimulusReflex

- Gem: 3.4.0

### External tools

- Ruby: [e.g. 2.7.2]
- Rails: [e.g. 6.1.0]

**Comment by leastbad** [comment]
Thank for raising this concern. We're on it!

**Comment by julianrubisch** [comment]
We could snatch a bit of code from Hotwire: https://github.com/hotwired/turbo-rails/blob/main/lib/tasks/turbo_tasks.rake#L1

I think this is solved pretty well, running an `rails app:template` in the installer, thus being able to run Thor actions.

That would be a bigger rewrite though, but I assume it could pay off?

**Comment by leastbad** [comment]
My suggestion is that we resolve this issue and fix the specific concern @jonsgreen located. We can then create an issue for a new and improved re-write for the next major release. This is precisely the wrong time to go deep on bike shedding when the script has 99% been working well. Even 429 hasn't been spotted failing in the wild! So far as I know, Jon is just eagle-eyed and prioritizing reading the code 👏 so he realized this could fall down.

**Comment by jonsgreen** [comment]
No eagle eyes. I actually bumped into it on our latest project and so I thought I would report it.
