### ISSUE TITLE
When devise uses `timeoutable` there is a session error authenticating a stimulus web socket.

### ISSUE THREAD

**Issue by hadees** [hopsoft/stimulus_reflex#437]
# Bug Report

## Describe the bug

When using `devise` with `:timeoutable` enabled via `devise :database_authenticatable, :timeoutable` warden throws an error trying to access the session to check `last_request_at`.

## To Reproduce

Follow the directions for setting up devise with `StimulusReflex`. 

Then add `:timeoutable` to the list of devise modules enabled in the model, in my case `user.rb`

## Expected behavior

I expected it to only throw an error when `last_request_at` was too big when comparing it to the `devise.rb` config.

## Screenshots or reproduction

```ruby
# frozen_string_literal: true

module ApplicationCable
  # Default connection for ActionCable
  class Connection < ActionCable::Connection::Base
    identified_by :current_user

    def connect
      Current.user = find_verified_user
      logger.add_tags 'ActionCable', Current.user.id
      self.current_user = Current.user
    end

    # this checks whether a user is authenticated with devise
    protected def find_verified_user
      verified_user = env['warden'].user
      return reject_unauthorized_connection if verified_user.blank?

      verified_user
    end
  end
end
```

```ruby
# frozen_string_literal: true

# Application wide Reflex behavior
class ApplicationReflex < StimulusReflex::Reflex
  #
  # Example:
  #
  #   # If your ActionCable connection is: `identified_by :current_user`
  delegate :current_user, to: :connection
  delegate :render_with_signed_in_user, to: ApplicationController
  #
  # Learn more at: https://docs.stimulusreflex.com
end
```

```
E, [2021-02-01T16:15:13.832533 #31862] ERROR -- : [ActionCable] [2ede8d32-50b8-48c3-96ef-8da2dbac1a8a] StimulusReflex::Channel Failed to invoke CartsReflex#update_cart! http://infrared-test.lvh.me:3000/ undefined method `[]' for nil:NilClass /Users/foobar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/warden-1.2.9/lib/warden/proxy.rb:246:in `session'
```

If applicable, add screenshots (errors, example of the behavior, etc.) to help explain your problem or post a link to a repository that replicates the issue.

### StimulusReflex

- Gem: 3.3.0
- Node package: 3.3.0

### External tools

- Ruby: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]
- Rails: Rails 6.1.1
- Node: v15.4.0

### Browser

- Browser chrome
- Version 88.0.4324.96 (Official Build) (x86_64)

**Comment by leastbad** [comment]
Hi Evan,

This is a new one for me!

First: I urge you to upgrade to SR 3.4.1. It won't fix your problem, but it's [so much better](https://docs.stimulusreflex.com/appendices/release-history#new-release-v-3-4-developer-happiness-edition). :)

I'm going to need a bit more information about when and where this error is happening:

1. The error mentions the update_cart! action method. Could you please attach your Reflex class?
2. Is this error happening right away after you login, or does it only start after the timeout eg. if you come back to your page

I'm curious: how does timeoutable usually work with Turbolinks? **Are you using Turbolinks?** I am assuming that it tries to send you back to the login screen, but of course ActionCable has no idea wtf is going on...

I'm trying to figure out if there's any kind of callback possible from the timeoutable module that we could use to tell ActionCable to disconnect someone who's been logged out.

**Comment by leastbad** [comment]
Here's how I would attack this...

https://github.com/heartcombo/devise/blob/master/lib/devise/hooks/timeoutable.rb

I would put a copy of `timeoutable.rb` in your `config/initializers`. Then on line 27, before `Devise.sign_out_all_scopes`, I would add this:
```rb
ActionCable.server.remote_connections.where(current_user: record).disconnect
```

After you restart puma, you should see that any connections are disconnected if the user goes to a new page and is logged out due to inactivity.

**Comment by leastbad** [comment]
Hey @hadees, could you let me know how it went with my suggestions? I don't want to leave you hanging!

**Comment by leastbad** [comment]
I don't like to close issues without knowing that they're resolved, but please know that we're here for you if this is somehow still a problem - we can always reopen later.
