### ISSUE TITLE
iFrame gets refreshed despite data-reflex-permanent

### ISSUE THREAD

**Issue by RolandStuder** [hopsoft/stimulus_reflex#452]
# Bug Report

In some cases iframes get refreshed when they shouldn't. This happens when sibling nodes get added / removed to a parent element of an iframe.
* The content is respected not change, but some aspect of the element/node is touched which makes the iframe reload. See last minute of the video below.

## To Reproduce

MVCE
https://github.com/RolandStuder/stimulus-reflex-morph-ifram-bug

## Expected behavior

iframe content is not reloaded

## Screenshots or reproduction

commented behavior here
https://www.loom.com/share/091433753868455fa6a4cf032e430058## Versions

### StimulusReflex

- Gem: stimulus_reflex (3.4.1)
- Node package: 3.4.1

### External tools

- latest StimulusReflexHarness, Ruby 2.7.2

### Browser

- Latest Chrome / Safari / Firefox

**Comment by RolandStuder** [comment]
Might be this issue here: https://github.com/patrick-steele-idem/morphdom/issues/200

**Comment by leastbad** [comment]
I've been working on this about 40 hours now, and I've sadly made zero real progress. I've asked for help from @snewcomer but he's likely very busy with @snewcomer things. This might just need to be documented as a warning so that I can move on with my life.

**Comment by leastbad** [comment]
@RolandStuder I think we should close this because it's an issue that can only be fixed in morphdom. 😿 

I'm going to attempt to add something about this to the docs: https://docs.stimulusreflex.com/appendices/troubleshooting#iframe-gets-refreshed-despite-data-reflex-permanent
