### ISSUE TITLE
Page morphs fail to refresh (blank operations hash) in Safari/Edge on staging

### ISSUE THREAD

**Issue by existentialmutt** [hopsoft/stimulus_reflex#453]
## Describe the bug

When my app is running on staging and production, and browsing with Safari (13.0.5) or Edge (88), page morphs fail to update the page.  Looking at the websocket messages, I see the reflex coming back from the server with a blank cableready operations hash.  This doesn't happen in other browsers, with selector morphs in Safari and Edge on staging, or in any browser running the site locally in development mode.

I've tried creating an MVCE with stimulus_reflex_harness and can't reproduce it there, so I guess it's something in my app that's screwing things up.  Any ideas on what could cause the operations hash to go blank, or suggestions on how I could approach debugging?

## Screenshots or reproduction

![Web_Inspector_—_staging_cumulusrisk_com_—_facility_profile](https://user-images.githubusercontent.com/90793/107435748-9048f200-6afa-11eb-96ca-d7851f77a1ae.png)

### StimulusReflex

- Gem: 3.4.1
- Node package: 3.4.1

### External tools

- Ruby: 2.7.2
- Rails: 6.1.1
- Node: 10.18.0

### Browser

Safari 13.0.5
Edge 88

**Comment by existentialmutt** [comment]
As soon as I asked I figured it out.  We have HTTP_BASIC authentication on the staging site and those browsers weren't sending credentials.  Fixed it by disabling the `authenticate_or_request_with_http_basic` before filter if `@stimulus_reflex` is true.

**Comment by leastbad** [comment]
I'll add this to the troubleshooting page! Sorry that you were having troubles.
