### ISSUE TITLE
Link for "read more about why we enable caching here" is broken

### ISSUE THREAD

**Issue by asyraffff** [hopsoft/stimulus_reflex#455]
# Bug Report

In [setup](https://docs.stimulusreflex.com/hello-world/setup) documentation,
I try to open the link in "**You can read more about why we enable caching here**." at here ;

![Screenshot 2021-02-10 at 14.25.29.png](https://cdn.hashnode.com/res/hashnode/image/upload/v1612938462033/oKoaVHBgb.png)

It will direct me to this [page](https://app.gitbook.com/@stimulusreflex/s/stimulusreflex/~/drafts/-MSU6Biq0jCNSes9e6mx/appendices/deployment#session-storage). But the page doesn't exist.
Seems like the link to the gitbook is broken.
## To Reproduce

Either direct the viewer to the gitbook link or to the Github documentation on this [section](https://github.com/hopsoft/stimulus_reflex/blob/master/docs/appendices/deployment.md#session-storage)

## Expected behavior

Expect to direct me to the Gitbook page about "why we enable caching". But, I found it in [Github](https://github.com/hopsoft/stimulus_reflex/blob/master/docs/appendices/deployment.md#session-storage) instead.

**Comment by leastbad** [comment]
Thanks so much, Amirul! I just pushed a fix, now.

More importantly, let me know if the explanation makes sense to you!
