### ISSUE TITLE
Uncaught exception when morph removes controllerElement

### ISSUE THREAD

**Issue by shubik22** [hopsoft/stimulus_reflex#459]
# Bug Report

## Describe the bug

When a reflex invocation results in the controller element being removed from the page, the serverMessage function, invoked by a `stimulus-reflex:server-message` event, will result in an uncaught exception:

```
stimulus_reflex.js:517 Uncaught TypeError: Cannot read property 'reflexError' of null
    at HTMLDocument.<anonymous> (stimulus_reflex.js:517)
    at b (utils.js:31)
    at cable_ready.js:316
    at Array.forEach (<anonymous>)
    at x (utils.js:52)
    at Object.dispatchEvent (cable_ready.js:313)
    at Object.R [as perform] (cable_ready.js:444)
    at t.received (stimulus_reflex.js:121)
    at action_cable.js:536
    at Array.map (<anonymous>)
    at t.notify (action_cable.js:535)
    at t.message (action_cable.js:369)
```

## To Reproduce

A simple reproduction:
1.  Create a div with id "replace-me"
2. Add a button inside the div with data-reflex="TestReflex#reproduce_error"
3. Inside TestReflex#reproduce_error, call `morph '#replace-me', ''`

## Expected behavior

An exception should not be thrown.

## Screenshots or reproduction

![image](https://user-images.githubusercontent.com/5737046/109402313-bc8dac80-7909-11eb-9ce2-1b10871ef091.png)

### StimulusReflex

- Gem: 3.4.1
- Node package: 3.4.1

**Comment by leastbad** [comment]
Hey Sam! Thanks so much for filing this.

I am having trouble reproducing this issue, however. We put a huge amount of effort into making this problem go away, so I'm surprised to see it still happening in v3.4.1.

https://github.com/leastbad/stimulus_reflex_harness/tree/reproduce_459

I created a branch on the harness project and implemented your reproduction steps (90% faithfully - I used different names) and it seems to work as expected:

`[fa135668] 1/1 ExampleReflex#test -> #replace-me via Selector Morph (inner_html)`

<img width="597" alt="chrome_2XvOIgSn4w" src="https://user-images.githubusercontent.com/38150464/109407941-0c449600-7953-11eb-9d8d-81c4ab9bcb71.png">

<img width="189" alt="chrome_C1HbLfXZ4p" src="https://user-images.githubusercontent.com/38150464/109407942-11094a00-7953-11eb-8c02-4731bcffa9cb.png">

Could you clone the repo/branch I linked to above and see if it works for you?

The other thing that doesn't really add up is that if you look at line 517 of `stimulus_reflex.js` in the commit that v3.4.1 was cut from, it's an empty line and nothing close to it operates on the reflexError property. **This suggests that you have something going on with your client package being out of sync.**

I would strongly consider blowing away your `node_modules` and re-running `yarn install` to be 100% sure things are straight.

**Comment by shubik22** [comment]
Thanks for the response and apologies, I realized I didn't accurately describe the reproduction steps.

I was able to reproduce the issue with your repo by making a slight modification.  Instead of calling morph, the error is caused by broadcasting an inner_html operation via cable_ready.  [This repo](https://github.com/shubik22/stimulus_reflex_harness/tree/reproduce_459) has the correct setup.

Here's the error:

<img width="1303" alt="Screen Shot 2021-03-01 at 9 09 56 AM" src="https://user-images.githubusercontent.com/5737046/109532813-5bcbb480-7a6e-11eb-862a-ce80452cb4c7.png">

And the code throwing the error:

<img width="801" alt="Screen Shot 2021-03-01 at 9 11 16 AM" src="https://user-images.githubusercontent.com/5737046/109532845-66864980-7a6e-11eb-9f0b-14a6b4823ce5.png">

**Comment by leastbad** [comment]
Hey Sam,

I'm chuckling because as you acknowledged, this an entirely different problem than what you originally described. It's not a use case that we'd covered since people usually do use Selector Morphs for this kind of thing.

However, I agree that this shouldn't generate an error. I'm going to make a small change and then accept your PR.

Thank you for spotting this!

**Comment by shubik22** [comment]
Thanks very much and apologies for the inaccurate original report!
