### ISSUE TITLE
"No route matches" in production

### ISSUE THREAD

**Issue by jsalik** [hopsoft/stimulus_reflex#465]
# Bug Report

## Describe the bug
```
Reflex ReflexName#method failed: No route matches "https://***"
/home/****/.rvm/gems/ruby-2.5.7/gems/actionpack-6.1.2/lib/action_dispatch/routing/route_set.rb:886:in `recognize_path_with_request' [https://***]
NOTE: StimulusReflex failed to locate a matching route and could not re-render the page.
```
![image](https://user-images.githubusercontent.com/6525630/110124396-5221b400-7dc2-11eb-8880-3407ea0de2f8.png)

## To Reproduce
In development environment everything works ok, but after deployment, in production errors occurs:
Maybe there is additional configuration needed? 

## Versions
- Gem: 3.4.1
- Node package: [e.g. 2.0.1]

### External tools
- Ruby: 2.5.7
- Rails: 6.1.2

**Comment by leastbad** [comment]
Hi Jarosław,

Could you verify that your SR gem + npm is 3.4.1 please? 4.3.1 isn't out yet. :wink:

Are you using `acts_as_tenant` or another gem that might be using Rack middleware to modify the URLs Rails receives behind the scenes? https://docs.stimulusreflex.com/hello-world/setup#rack-middleware-support

**Comment by jsalik** [comment]
Sorry, it's 3.4.1 of course.
`{
  "name": "xxx",
  "private": true,
  "dependencies": {
    "@rails/actioncable": "^6.0.0",
    "@rails/actiontext": "^6.0.3-4",
    "@rails/activestorage": "^6.0.0",
    "@rails/ujs": "^6.0.0",
    "@rails/webpacker": "4.3.0",
    "animate-sass": "^0.8.2",
    "bootstrap": "^4.5.3",
    "bootstrap-select": "^1.13.18",
    "i18n-js": "^3.8.0",
    "jquery": "^3.5.1",
    "ladda": "^2.0.1",
    "loaders.css": "^0.1.2",
    "nouislider": "12.1.0",
    "pe7-icon": "^1.0.4",
    "popper.js": "^1.16.1",
    "rails-erb-loader": "^5.5.2",
    "slick": "^1.12.2",
    "slick-carousel": "^1.8.1",
    "stimulus": "^2.0.0",
    "stimulus-remote-rails": "^2.0.0",
    "stimulus_reflex": "3.4.1",
    "trix": "^1.2.0",
    "turbolinks": "^5.2.0"
  },
  "version": "0.1.0",
  "devDependencies": {
    "webpack-dev-server": "^3.11.0"
  }
}
`
`source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.7'

gem 'active_model_serializers', '~> 0.10.6'
gem 'avatarly'
gem 'awesome_print'
gem 'bootsnap', '>= 1.4.2', require: false
gem 'browser'
gem 'countries'
gem 'devise'
gem 'hiredis'
gem 'i18n-js'
gem 'image_processing', '~> 1.2'
gem 'jbuilder', '~> 2.7'
gem 'money-rails', '~>1.12'
gem 'puma', '~> 4.1'
gem 'rails', '= 6.1.2'
gem 'rails-i18n'
gem 'rails-settings-cached'
gem 'recaptcha'
gem 'redis', '>= 4.0', require: ['redis', 'redis/connection/hiredis']
gem 'redis-namespace'
gem 'redis-session-store'
gem 'sass-rails', '>= 6'
gem 'sendgrid-actionmailer'
gem 'sentry-rails'
gem 'sentry-ruby'
gem 'sidekiq'
gem 'simple_form'
gem 'stimulus_reflex', '= 3.4.1'
gem 'stripe'
gem 'stripe_event'
gem 'turbolinks', '~> 5'
gem 'webpacker', '~> 4.0'

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'sqlite3', '~> 1.4'
end


group :development do
  gem 'capistrano', '~> 3.14', require: false
  gem 'capistrano-bundler', '>= 1.1.0'
  gem 'capistrano-rails', '~> 1.6', require: false
  gem 'capistrano-rvm'
  gem 'capistrano-sidekiq'
  gem 'capistrano3-puma', '~> 5.0.0'
  gem 'listen', '~> 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console', '>= 3.3.0'
end

group :test do
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  gem 'webdrivers'
end

group :production do
  gem 'pg'
end

gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
`

**Comment by leastbad** [comment]
Hi again,

A simple "yes" would have been fine! lol

Let me know if you have read and understood the documentation on enabling Rack middleware for your Page Morphs.

**Comment by jsalik** [comment]
Well, i think so :) I'm not using any gems like acts_as_tenant or apartment where aditional rack middleware is needed and i'm not using my own middlware, that't why i'm stack with this error

**Comment by leastbad** [comment]
Does it run in the production environment on your local machine? `RAILS_ENV=production rails s` I think.

There is no particularly good reason for it to stop working in production. Feel free to clone https://github.com/leastbad/stimulus_reflex_harness and provide a reproduction, or you can share a link to your repo and we can check out what might be going wrong. Otherwise I'm just guessing.

At the very least, can you please post the content of your `invitations_reflex.rb`?

**Comment by jsalik** [comment]
I checked production enviroment on my local machine and it works! So you are right, i'ts not related to production itself

**Comment by leastbad** [comment]
Well, in that case I'm going to close this issue for now. Please do report back if you figure out what was going on in your hosting environment. FWIW SR is widely deployed without issue, so I'm confident that you'll crack the code.

**Comment by jsalik** [comment]
Hi again, it turned out that i was missing:
`proxy_set_header Host $http_host;`
in nginx vhost configuration.

**Comment by leastbad** [comment]
That's really useful intelligence! What section does that get set in?

**Comment by jsalik** [comment]
In location entry, for exmaple: 
`server {
  listen 80;
  server_name example.com;
  location / {
    ...
    proxy_set_header Host $http_host;
    ...
  }
}`
