### ISSUE TITLE
Lost Instance Variables

### ISSUE THREAD

**Issue by jonsgreen** [hopsoft/stimulus_reflex#471]
## Describe the bug

Calling controller in a before_reflex keeps instance variables set in the reflex from being accessible in the view. Discord conversation [here](https://discord.com/channels/629472241427415060/733725826411135107/821352741020368907).

## To Reproduce

Here is an MVCE to demonstrate the behavior: https://github.com/jonsgreen/stimulus_reflex_input_bug/tree/lost-instance-variables-bug. 

If you update the message comment you will see that the message is updated but the `@comment` set in the does not transfer to the view.  If you comment out: https://github.com/jonsgreen/stimulus_reflex_input_bug/blob/lost-instance-variables-bug/app/reflexes/message_reflex.rb#L4 then it does. 

## Expected behavior

Expect all instance variables set in a reflex to be available when rendering. 

### StimulusReflex

- Gem: [e.g.  3.4.1]
- Node package: [e.g. 3.4.1]

### External tools

- Ruby: [e.g. 2.6.5]
- Rails: [e.g. 6.0.3]

**Comment by leastbad** [comment]
Hi Jonathan,

#493 should address this. If you have a second, let me know what you think!
