### ISSUE TITLE
Re-assignment of constant `reflexRoot`

### ISSUE THREAD

**Issue by scottbarrow** [hopsoft/stimulus_reflex#473]
# Bug Report

_Please help us help you by filling out any applicable information in this template and removing the rest!_

## Describe the bug
upon upgrading to vite-rails, it has identified a constant reassignment

## To Reproduce
Install vite-rails

## Expected behavior

No errrors

## Screenshots or reproduction
<img width="1152" alt="Screen Shot 2021-03-17 at 2 51 39 PM" src="https://user-images.githubusercontent.com/5571736/111545411-470c4380-8733-11eb-9dfb-6c3615662a2f.png">

### StimulusReflex

- Gem: [e.g. 3.3.0]
- Node package: [e.g. 3.4.1]

### External tools

- Ruby: [e.g. 2.7]
- Rails: [e.g. 6.1]
- Node: [e.g. 15.5.0]

### Browser
n/a

**Comment by cromega** [comment]
Could we have a 3.4.2 release with this in? and potentially other fixes that make the library usable with esbuild please?

**Comment by leastbad** [comment]
> Could we have a 3.4.2 release with this in? and potentially other fixes that make the library usable with esbuild please?

Yes! Coming very soon. This is what is currently in the #announcements channel on our Discord:

I just pushed a new update to the upcoming SR installer that supports **Shakapacker** and **Vite**. SR now supports all major bundlers in their default configuration:

Rails 6.1: webpacker 5.4.3, shakapacker, vite
Rails 7: importmap, esbuild, shakapacker, vite

You don't need to have SR/CR checked out locally; just create a `rails new` and pop this into your `Gemfile`:
```ruby
gem "cable_ready", github: "stimulusreflex/cable_ready", branch: "master"
gem "stimulus_reflex", github: "stimulusreflex/stimulus_reflex", branch: "new_installer"
```
and this into your `package.json`:
```json
"dependencies": {
  "stimulus_reflex": "stimulusreflex/dev-builds#stimulus_reflex/0c16f4f"
},
"resolutions": {
  "cable_ready": "cableready/dev-builds#cable_ready/3531e43"
}
```
Then run `rails stimulus_reflex:install`. **That's it.**

Of course, there's lots more information in https://github.com/stimulusreflex/stimulus_reflex/pull/610 but you can just skip to the good part.
