### ISSUE TITLE
Formatting issues on README

### ISSUE THREAD

**Issue by andrewmcodes** [hopsoft/stimulus_reflex#48]
# Bug Report

## Describe the bug

Looks like there are some formatting issues on the README. 

ex: 
>{% code-tabs %} {% code-tabs-item title="app/javascript/controllers/index.js" %}

## Proposed Solution

Maybe we should pull some stuff out of the README now that we are using gitbook. We can move a lot of this into the docs/ folder, which would make updating the gitbook updates easier. 

Thoughts @hopsoft?

**Comment by hopsoft** [comment]
Would love some help getting the docs organized. I spent some time building them out on GitBook and setup the integration after. I wasn't quite sure what would happen. I think the GitBook hosted docs look great, but I'm not thrilled with how it dumped everything on root... with markdown that doesn't render on GitHub. If we can move stuff to a docs directory and have a cleaner main README, let's do it.

**Comment by andrewmcodes** [comment]
@hopsoft if you can somehow give me access, I’ll take this on.

**Comment by andrewmcodes** [comment]
Feel free to checkout the repo. Latest commit is probably most important. https://github.com/andrewmcodes/rails_markdown_live_render
