### ISSUE TITLE
Trying to get this working in Rails 6

### ISSUE THREAD

**Issue by pjforde1978** [hopsoft/stimulus_reflex#8]
In Rails 6, there is no app/assets/javascripts folder, so I can't figure out how to get the dependency on stimulus_reflex properly referenced. What's the best way to import/require from within a gem? I checked and it doesn't seem like there is a stimulus_reflex package on npm, which might be the magic solution.

I could grab the js from the gem and include it directly, but that seems super gauche.

If you have even a single line of require() syntax (including the .start() call, if any) I would be indebted.

**Comment by hopsoft** [comment]
I just updated this to be more Rails 6 friendly and bumped the version to 1.0. Let me know if you have issues with it going forward.
