### ISSUE TITLE
Slack Community

### ISSUE THREAD

**Issue by darkrubyist** [hopsoft/stimulus_reflex#90]
# Feature Request

Please create a Slack Community. Would love to join in this wonderful community.

Best Regards
Andrew

**Comment by pjforde1978** [comment]
Hey Andrew, that's actually a really good idea. We'd love to be able to help people get started with as little friction as possible.

In the meantime, how are you making out with your first StimulusReflex experiments? Anything you got stuck on, or need help with? Anything we could be doing better?

Curious, too, how you found out about the project.

**Comment by darkrubyist** [comment]
Hey @pjforde1978, thank you for the fast response.

I heard about StimulusReflex from the Stimulus Discourse forum, I think around 2 months ago.

I didn't used StimulusReflex until now, but I'm planning to start using it. :)

I will go through the documentation and the expo examples and will try to use it by the end of the week.

Best
Andrew

**Comment by hopsoft** [comment]
We really want to get this setup. We've been discussing options for our community home. We're currently considering the following options (in no particular order). Would love to see other people's preferences.

- Gitter
- Slack
- Discord
- Discourse

**Comment by darkrubyist** [comment]
Personally I would vote for Slack or Discord. 
Would love to hear other people's preferences as well.

**Comment by pjforde1978** [comment]
I’ve used Slack extensively, and like Discourse very much as well. 

Here’s my biases: as someone truly prepared to personally roll up my sleeves and help a huge number of people, I am genuinely worried that Slack is massively distracting and really kind of terrible at preserving the sorts of wisdom that devs go searching for when they have problems.

Slack conversations are conversations and can get off course. People tend to keep forum threads a bit more on topic.

I also feel like there’s a lower cognitive barrier to searching or posting on a forum than there is to adding a Slack team to your profile.

**Comment by julianrubisch** [comment]
Slack and Discourse are my favorites, too.

I've got some issues at the moment that don't belong in the issue tracker, so I'd really like to see that set up 👍

**Comment by pjforde1978** [comment]
Worth revisiting: https://drewdevault.com/2015/11/01/Please-stop-using-slack.html

FWIW, I was a teenage IRC addict so perhaps that's why I recognize the importance of focus. Continuous partial attention is cancer to high-quality output.

**Comment by andrewmcodes** [comment]
@darkrubyist @julianrubisch @pjforde1978 

We created a discord and are also working on setting up discourse. 

[discord link](https://discord.gg/XveN625)

**Comment by hopsoft** [comment]
I agree with @pjforde1978 that async longer form communication is preferable (i.e. Discourse); however, there are times when a quick chat with someone can quickly resolve a problem. The plan is to support both async and sync communication options. We're kicking the tires on Discord for sync and I'll be setting up Discourse for async this weekend sometime.

**Comment by darkrubyist** [comment]
Yes, I agree with both of you. 
The benefit of using Discord is that is easier to resolve a problem with a real time chat.
The benefit of Discourse is the SEO. Everything will be indexed in Google and Stimulus Reflex will have more exposure to the world.

Maybe we can add some badges on the Readme to let people know about Discord and Discourse.

**Comment by julianrubisch** [comment]
Thank you everyone! This is great news!

Also, should we somehow include that in the code of conduct?

**Comment by hopsoft** [comment]
I love the idea of making the code of conduct explicit in each of these communication channels. @andrewmcodes will you help look into what might be required for that?

I have applied for the free hosting that Discourse offers to qualifying open source projects and hope to have an answer from them in about 2 days. See: https://free.discourse.group

**Comment by hopsoft** [comment]
We've been approved by Discourse. The community forum is hosted at: https://stimulus-reflex.discourse.group

Note that I may move us to Gitter for the chat given that it removes some of the friction for signing up and participating. i.e. Allows SSO with GitHub etc...
