### ISSUE TITLE
Custom Stimulus schema breaks Reflex

### ISSUE THREAD

**Issue by nickyvanurk** [hopsoft/stimulus_reflex#91]
## Describe the bug

Reflex ignores the schema set in Stimulus. It assumes Stimulus will always use the default schema.

Line 220 in javascript/stimulus_reflex.js
```
 if (actionValue) element.setAttribute('data-action', actionValue)
```
Hardcodes the 'data-action' attribute.

In our project we use a custom schema as follows:

```
const application = Application.start(document.documentElement, {
  controllerAttribute: 'data-controller',
  actionAttribute: 'data-do',
  targetAttribute: 'data-target'
});
```
Because we had a conflict with another plugin, cropperjs.

Feedback would be appreciated.

**Comment by hopsoft** [comment]
Great report. We need to update Reflex to support custom Stimulus schema.

**Comment by nickyvanurk** [comment]
After reviewing both Stimulus and Reflex it can probably be fixed by simply changing 'data-action' to:
```
application.schema.actionAttribute
```

**Comment by pjforde1978** [comment]
To your question about pull requests, StimulusReflex forced me to finally figure out the contribution workflow. Happy to help off-line if you want to DM me, but the basic idea is that you fork the project to your own account, make a feature branch, change that feature branch, commit it, push it, and when you push it, GitHub will prompt you to open a PR from your feature branch back to hopsoft:master. And then we all win!

**Comment by nickyvanurk** [comment]
Thank you for the kind words @pjforde1978 I am implementing a private chat feature. I was doing the things Reflex does by hand but then a colleague of mine told me about the Reflex gem.

**Comment by nickyvanurk** [comment]
I made a pull request, 2 simple changes in the code. That should fix the issue.

**Comment by pjforde1978** [comment]
Make sure that you check out the chat example on the StimulusReflex Expo site!

There is a feature PR on hold waiting for a real use case. Could you peek at #87 and tell us whether that would be useful to you?

Providing an alternative schema for `data-reflex` is a lot more involved but still probably possible. It’s a lot more prevalent through our codebase for obvious reasons, but there’s further issues because we have additional attributes like `data-reflex-permanent` that have (currently) hard-coded server-side strings in the Ruby code. It’s hard to imagine how we could accommodate this without passing a lot of meta-metadata with each call.

We’ll have to talk about this. Changing the Stimulus schema is __a thing__ and action is a much more common term than reflex, which we’ve never suggested people could change.

Lots to think about.

**Comment by nickyvanurk** [comment]
@pjforde1978 #87 Is actually what I was already looking for! Would be really useful in my chat feature for appending new conversations and messages.

**Comment by pjforde1978** [comment]
Not paying this guy, @hopsoft. I swear! 🤓

**Comment by nickyvanurk** [comment]
Any indication when this enhancement will, if possible, be accepted? Manualy building the gem and including it in my project doesn't seem to work. Also, in my gemfile when I use `gem "stimulus_reflex", git: 'https://github.com/nickyvanurk/stimulus_reflex', branch: 'stimulus-custom-schema-support'` you would think it will work, right? But when I inspect the stimulus_reflex.js in my browser while the project is running it still shows the old line of code (line 220). Any feedback would be appreciated.

**Comment by pjforde1978** [comment]
Usually what you do is go to your project root folder and run `yard link stimulus_reflex` (assuming you’re using yarn). If you’re still seeing the old js, go into node_modules, delete stimulus_reflex, run yarn link again and then finally, restart webpacker via bin/webpack or bin/webpack-dev-server

Let us know how things turn out. Good luck!

**Comment by nickyvanurk** [comment]
@pjforde1978 Is there anyway we can communicate outside of GitHub? Could use some input on my current project :) You can also email me, my mail is listed on my profile.

**Comment by darkrubyist** [comment]
> @pjforde1978 Is there anyway we can communicate outside of GitHub? Could use some input on my current project :) You can also email me, my mail is listed on my profile.

Hey @nickyvanurk please have a look the following issue: #90 
Stimulus Reflex has a Discord server where you can chat real-time. 

You can join here:
https://discord.gg/XveN625
