### ISSUE TITLE
Docs formatting broken in Persistence section

### ISSUE THREAD

**Issue by szTheory** [hopsoft/stimulus_reflex#93]
# Bug Report

The example formatting is not displaying properly at https://docs.stimulusreflex.com/persistence#instance-variables

## Screenshots or reproduction

<img width="840" alt="screenie" src="https://user-images.githubusercontent.com/28652/68074889-2712f480-fd77-11e9-83e4-d0225a0dde3f.png">

**Comment by pjforde1978** [comment]
I'm really sorry about this, @szTheory. I have to bring this page up to the standard of the rest of the docs, ASAP.

In the meantime, please consider me available to answer any questions you might have.

**Comment by szTheory** [comment]
Thank you. It displays fine on https://github.com/hopsoft/stimulus_reflex/blob/master/docs/persistence.md so I'm referencing that for now.

**Comment by pjforde1978** [comment]
@szTheory I don't have permissions to close this ticket, but I wanted to say that the docs got cleaned up a while back. I really appreciate the nudge!
